### ISSUE TITLE
Add "Remove-VsteamGitRef" command

### ISSUE THREAD

**Issue by TechnicalVegeta** [DarqueWarrior/vsteam#100]
Feature:
Need to Add "Remove-VSTeamGitRef" command similar to "Get-VSTeamGitRef" command.

Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

Remove-VSTeamGitRef -ProjectName $Projname  -RepositoryID $RepID

Actual behavior
---------------

Remove-VSTeamGitRef command not available.

Environment data
----------------

```powershell
> $VSTeamVersionTable

```

```powershell
> $PSVersionTable

```

**Comment by DarqueWarrior** [comment]
Just curious why not just use git?  a GitRef is just a branch.
