### ISSUE TITLE
Add-VSTeamUser - add option for specifying licensing source (e.g. MSDN)

### ISSUE THREAD

**Issue by janegilring** [DarqueWarrior/vsteam#106]
The Add-VSTeamUser currently (per version 4.0.9) let's us specify -License with the following valid options:
[ValidateSet('Advanced', 'EarlyAdopter', 'Express', 'None', 'Professional', 'StakeHolder')]

In the UI we can also add users with an access level called "Visual Studio Subscriber". Under the hood, this seems to specify a Licensing Source of type MSDN.

Some relevant links from the documentation:
[LicensingSource](https://docs.microsoft.com/en-us/rest/api/vsts/memberentitlementmanagement/user%20entitlements/get?view=vsts-rest-4.1#licensingsource)
[MsdnLicenseType](https://docs.microsoft.com/en-us/rest/api/vsts/memberentitlementmanagement/user%20entitlements/get?view=vsts-rest-4.1#msdnlicensetype)
[Access Level](https://docs.microsoft.com/en-us/rest/api/vsts/memberentitlementmanagement/user%20entitlements/get?view=vsts-rest-4.1#accesslevel)

It would be nice to be able to also add users with the licensing source MSDN by using Add-VSTeamUser.

**Comment by DarqueWarrior** [comment]
I created a branch and tested using MSDN as a license type and it is failing. I will have to do some more research.
