### ISSUE TITLE
Add-VSTeamUser -License None is not valid

### ISSUE THREAD

**Issue by janegilring** [DarqueWarrior/vsteam#107]
Steps to reproduce
------------------

```powershell

PS C:\> $AzureDevOpsNewUserRequest = Add-VSTeamUser -Email user@contoso.com -License None
PS C:\> $AzureDevOpsNewUserRequest.operationResult.errors.value
A user cannot be assigned an Account-None license.

```

Expected behavior
-----------------

A user of the type Stakeholder should be created

Actual behavior
---------------

Error message: "A user cannot be assigned an Account-None license."

Environment data
----------------

No output from $VSTeamVersionTable. However, the module version is 4.0.9.

$PSVersionTable:
```powershell
PSVersion                      5.1.14393.2485
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2485
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by DarqueWarrior** [comment]
Per the documentation none is valid. I will confirm with the team if the docs are wrong.

**Comment by MichelZ** [comment]
I think none is valid, but only with "additional" options (licensingSource / msdnLicenseType)

I'd close this one in favor of #106 @DarqueWarrior

**Comment by SebastianSchuetze** [comment]
closing this issue as suggested by @MichelZ . If the problem still appears with the new implementation then we can reopen it @janegilring
