### ISSUE TITLE
Unable to find type [VSTeamVersions]

### ISSUE THREAD

**Issue by ansariwn** [DarqueWarrior/vsteam#109]
Steps to reproduce
------------------
1. On a windows Server 2012 R2 machine.
2. Install latest VSTeam powershell module.
3. Create a new PowerShell script (ps1) file and call 'Import-Module -Name VSTeam' in the script.
4. Execute the script in PowerShell console.

Expected behavior
-----------------
The PowerShell module VSTeam should import successfully.

Actual behavior
---------------
An error is thrown, please see the log output below
```
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\VSTeam.psd1'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\Approvals.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\builds.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\cloudSubscriptions.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\repositories.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\policies.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\releaseDefinitions.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\releases.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\serviceendpoints.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\team.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\teammembers.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\teams.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\tfvc.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\users.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\workitems.ps1xml'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\pullrequest.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\formats\Approvals.format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\formats\builds.format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\formats\policyTypes.format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\formats\profile.format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\formats\serviceendpoints.format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\formats\serviceendpointTypes.format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\formats\team.format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\formats\users.format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\formats\workitemTypes.format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\formats\workitems.format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\formats\vsteamPSDrive.format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module VSTeam.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\src\teamspsdrive.ps1'.
VERBOSE: Dot-sourcing the script file 'C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\src\teamspsdrive.ps1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\src\team.psm1'.
Unable to find type [VSTeamVersions].
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\src\team.psm1:504 char:1
+ [VSTeamVersions]::ModuleVersion = _getModuleVersion
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (VSTeamVersions:TypeName) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TypeNotFound

Import-Module : The module to process 'C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\src\team.psm1', listed
in field 'NestedModules' of module manifest 'C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\VSTeam.psd1' was
not processed because no valid module was found in any module directory.
At C:\ReleaseManagement\InstallScripts\WindowsUpdateMonitor.ps1:20 char:1
+ Import-Module -Name VSTeam -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (VSTeam:String) [Import-Module], PSInvalidOperationException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Environment data
----------------

```powershell
> $VSTeamVersionTable

```

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Please note that if I use VSTeam version 3.0.x the module is imported successfully without any errors.

**Comment by KaiWalter** [comment]
can also reproduce it on a Win10 system

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.1292
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1292
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by KaiWalter** [comment]
same effect when importing module from cloned repo in some script:
```powershell
import-module C:\...\vsteam\VSTeam.psd1 -verbose
```

**Comment by DarqueWarrior** [comment]
Looking into this now.

**Comment by DarqueWarrior** [comment]
I just RDPed into a Windows Server 2012 R2 machine and installed 4.0.10 as administrator.
I then created a file named import.ps1 with the following in it:
```Import-Module -Name VSTeam -Verbose```
When I run the script:
```. .\import.ps1```
I don't get any errors. 
Can you see if you have mulitiple versions installed?
```Get-Module VSTeam -ListAvailable```
Do you see multiple versions?

**Comment by ansariwn** [comment]
I don't have multiple versions installed that I can see. Please see the output below:
```Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.
PS C:\Users\myusername> Get-Module vsteam -ListAvailable
    Directory: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   4.0.10     VSTeam                              {Add-VSTeamAzureRMServiceEndpoint, Add-VSTeamSonarQubeEndp...
```

- I create a fresh Windows Server 2012 R2 in AWS using CloudFormation.
- I install VSTeam module as administrator.
- I open windows Powershell ISE, I create new ps1 file with the following in it:
- - Import-Module -Name VSTeam -Verbose
- I close windows PowerShell ISE.
- I open a new Windows PowerShell command prompt.
- I browse (cd) to the directory containing the new ps1 file and I execute it.
- I see the following errors.

```
PS C:\ReleaseManagement> .\test.ps1
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\VSTeam.psd1'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\VSTeam\4.0.10\types\Approvals.ps1xml'.
...
VERBOSE: Populating RepositorySourceLocation property for module VSTeam.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\src\teamspsdrive.ps1'.
VERBOSE: Dot-sourcing the script file 'C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\src\teamspsdrive.ps1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\src\team.psm1'.
Unable to find type [VSTeamVersions].
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\src\team.psm1:504 char:1
+ [VSTeamVersions]::ModuleVersion = _getModuleVersion
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (VSTeamVersions:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Unable to find type [VSTeamVersions].
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\src\team.psm1:507 char:33
+ Set-VSTeamAPIVersion -Version $([VSTeamVersions]::Version)
+                                 ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (VSTeamVersions:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Set-VSTeamAPIVersion : Cannot validate argument on parameter 'Version'. The argument "" does not belong to the set
"TFS2017,TFS2018,VSTS" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the
command again.
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.10\src\team.psm1:507 char:31
+ Set-VSTeamAPIVersion -Version $([VSTeamVersions]::Version)
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-VSTeamAPIVersion], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Set-VSTeamAPIVersion

VERBOSE: Importing function 'Add-VSTeamAccount'.
...
PS C:\ReleaseManagement>
```

**Comment by DarqueWarrior** [comment]
Are you able to use the module from PowerShell? Does it only fail when called from Scripts?

I am also not sure why you need to import the script again. Once you install as an Admin it should be auto loaded and available to your script. 

Can you share your Get-ExecutionPolicy output?  Mine is RemoteSigned.

**Comment by KaiWalter** [comment]
Only a wild guess : execution context / scope is different when imported from a script compared to importing from the command line. Class definition for ```VSTeamVersions``` is not added to the scope of the script.
This must somehow relate to the breaking change from v3 to v4.

**Comment by DarqueWarrior** [comment]
I am still stumped on why I can't repro. I believe you it is throwing for you but I can't seem to get it to do that. So I am thinking it is an environmental issue or it would be breaking for me as well.  We need to figure out how I can repro as well so we can identify the culprit.

**Comment by KaiWalter** [comment]
@DarqueWarrior  - I now have a reproducible case on a plain / new Windows 2016 Server (Azure VM) - I do it again and record the steps

**Comment by quintessential5** [comment]
I don't know if this helps, because it doesn't seem like it would be very reproducible, but on a win 10 machine with VSTeam 4.0.12, I was able to ipmo fine, but...
`Add-VSTeamAccount -Level Process -PersonalAccessToken <validToken> -Account <accountName> -Version VSTS`
...produces a bunch of "Unable to find type [VSTeamVersions]" exceptions.

**Comment by DarqueWarrior** [comment]
When I get a moment I will try @KaiWalter steps to repro and see if I can get to the bottom of this.

**Comment by tkaepp** [comment]
I had to load it with `Using module "C:\Program Files\WindowsPowerShell\Modules\VSTeam\4.0.12\VSTeam.psd1"` Apparently classes aren't loaded when using `Import-Module`

Hope that helps.

**Comment by stefanstranger** [comment]
I've the same issue. When running a vsteam command using version 4.0.12 I get a whole bunch of Unable to find type [VSTeamVersions].
At C:\Users\stefstr\Documents\WindowsPowerShell\Modules\vsteam\4.0.12\src\team.psm1:428 char:13
+             [VSTeamVersions]::Version = 'VSTS'
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (VSTeamVersions:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

errors.

**Comment by TomBri72** [comment]
Having same issue here on Win7. Install (from command line or script) works fine but command execution (e.g. Add-VSTeamAccount) from command line or script results in many 
Unable to find type [VSTeamVersions]

**Comment by DarqueWarrior** [comment]
I am going to call in some big guns in the PowerShell world to help me figure this out.

**Comment by SteveL-MSFT** [comment]
Not able to repro on Win10, Win2k12, nor macOS running `Get-VSTeam`.  For those who are hitting an issue, perhaps try using `powershell -noprofile` to eliminate the possibility something in the profile is causing issues?

**Comment by liamfoneill** [comment]
I also have this issue - I am trying to install in on the Azure DevOps hosted agents VS2017 with the following code:

# Installs Azure DevOps PowerShell Library
Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
Install-Module -Name VSTeam -Force -Verbose -Scope CurrentUser
Import-Module -Name VSTeam

Am I doing it right?

**Comment by DarqueWarrior** [comment]
I don't think you need the Import-Module. The install should also import it for you. When I run the module through integration testing I just call Install-module without the import after. Can you give that a try?

**Comment by DarqueWarrior** [comment]
Can someone having this issue please Can you share your Get-ExecutionPolicy output? Mine is RemoteSigned.

**Comment by liamfoneill** [comment]
I was able to figure it out - I had the VSteam module installation as part of a script executed by the Azure PowerShell task on Azure DevOps. As soon as I changed it to the regular PowerShell task it worked!
________________________________

**Comment by TomBri72** [comment]
Get-ExecutionPolicy output: RemoteSigned

**Comment by DarqueWarrior** [comment]
Great news. I have a machine where I can duplicate this. Unfortunately I am about to start three weeks for travel. But I should be able to get to the bottom of this.

**Comment by NinoCapo** [comment]
Not sure if this helps, but this morning I was having the same issue after I installed the module from the 64bit window.  Just for giggles I tried it again from the x86 window, it worked, but I noticed it was referencing the module in C:\Program Files\WindowsPowerShell instead of x86 .  After that I tried using it again from the 64bit window and everything worked fine.  I can't really explain it.   I work from a Windows 10 Pro machine.

**Comment by DarqueWarrior** [comment]
Thanks for the data.  I am working a huge restructure of the module that might help with this. Once it is out it will be version 6.0.

**Comment by DarqueWarrior** [comment]
Can someone who could repo this please re-test with version 6.0.x?

**Comment by KaiWalter** [comment]
@DarqueWarrior I checked **positive** with my reproducible setup (see my comment on Oct 20, 2018) and one of my regular machines.

**Comment by DarqueWarrior** [comment]
Hey @KaiWalter you re-tested with 6.0.x and it still does not load?

**Comment by KaiWalter** [comment]
@DarqueWarrior, sorry "checked positive" seems a bit confusing. I re-tested on 3 different setups (on 2 of them I had problems and the module was not loading with 5.x) and now it is loading and **working perfectly!**

**Comment by DarqueWarrior** [comment]
Got it. So I can close these finally!  :). Thanks for confirming.
