### ISSUE TITLE
Update-VSTeamWorkItem

### ISSUE THREAD

**Issue by kardinal3000** [DarqueWarrior/vsteam#115]
Hello @DarqueWarrior  I have a quick question... Do you have a plan to add new cmdlet **Update-VSTeamWorkItem**?

Many thanks for all of this I mean "VSTeam" 👍

**Comment by DarqueWarrior** [comment]
I have been pretty slammed. Most of the latest changes have come via pull requests by the community. If you want to take a crack at it go ahead and submit a pull request.

**Comment by DarqueWarrior** [comment]
Are there particular fields you want to update? Allowing all will be very tough. But if only a few we might be able to add those and update as requirements dictate.

**Comment by DarqueWarrior** [comment]
Adding support for the items you can set when you create a work item.

**Comment by DarqueWarrior** [comment]
Fixed in PR #124
