### ISSUE TITLE
Ability to manage team membership for projects

### ISSUE THREAD

**Issue by klabranche** [DarqueWarrior/vsteam#116]
I'm sorry for adding an issue for likely a misunderstanding on my part.

I want to be able to add a group to a project team.   It doesn't appear to be possible?  I'm on TFS 18 on prem.  The Add-VSTeamUser returns "this account does not support member entitlement" and I'm not sure it's the right call.  I can add users/groups to the team(s) in a project via the UI.  I'm working on converting via a script a large number of TFS 15 (TFVS repos) over to a new TFS 18 server and GIT.  Having to manually add groups to the project teams would be a bummer.

**Comment by DarqueWarrior** [comment]
The error message is because the REST API that supports that was not in TFS 2018 at the time the module was created. I will see if that has changed and what API version is available in 2018.

**Comment by DarqueWarrior** [comment]
I just used Get-VSTeamOption and did not see any APIs that would support user management.

**Comment by klabranche** [comment]
Bummer, I was hoping I was doing something foolish.  :-)

**Comment by DarqueWarrior** [comment]
Thanks. There will be future updates to TFS. I believe the next major release will be Azure DevOps Server and I bet it will come with a new version of the API which may support it at that time.

**Comment by cwelde** [comment]
Hi Darque,

I've also needed to do what klabranche was trying to do and stumbled upon this post, proving it is not possible with these API versions (I'm on TFS 2017).

Is there another solution you recommend/might be able to point me to, as far as creating groups in TFS and configuring their permissions with PowerShell?

**Comment by DarqueWarrior** [comment]
Let me speak to the TFS/AzD team and see if I can find anything.
