### ISSUE TITLE
Add-ReleaseDefinition question

### ISSUE THREAD

**Issue by l0010o0001l** [DarqueWarrior/vsteam#117]
Heya,

I am wondering if anyone knows of a simple, good way to generate the release definition json file the `-inFile` parameter expects. I'm aware you can create a release definition in UI and then export it as JSON, however, I'm looking for a straightforward way to generate a well-formatted release definition JSON file not in UI. Apologies if this question is out of the scope of vsteam's project goals.

Thank you for your time!

**Comment by DarqueWarrior** [comment]
I am not aware of any other way. The JSON files have used were all created via the Export of one I created in the UI first.
