### ISSUE TITLE
Does the progress bar when deleting, and creating object add value?

### ISSUE THREAD

**Issue by DarqueWarrior** [DarqueWarrior/vsteam#119]
When you delete a project there is a progress bar that moves back and forth to indicate work is being down. However, when using the Azure PS module there is no progress bar for long running tasks like deleting a Resource Group. 

Should we drop this from this module as well?

Does anyone feel the module is better off having the progress bar?

**Comment by FriedrichWeinmann** [comment]
Well ... truth be told, I don't have any strong feelings either way.
One of the reasons that people often drop it is that it costs performance, depending on how often you refresh it (disabling it on Invoke-WebRequest in PS5.1 will cut the download time to ~1/3 of what it used to be).
That said, so long as it isn't refreshed too frequently, the cost isn't much of a factor - and if it's waiting for a remote / background task where the main thread would be idling anyway, it won't have _any_ impact on performance.

Given that anybody bothered by it can easily disable the progress bar:
```powershell
$ProgressPreference = 'SilentlyContinue'
```
I see no reason to drop it.

**Comment by akishaha** [comment]
Even I don't see a much valid point in dropping this feature.

**Comment by DarqueWarrior** [comment]
Thanks to https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-6#progresspreference I will be closing this issue.
