### ISSUE TITLE
Command name clashes with some commands in the MicrosoftTeams module

### ISSUE THREAD

**Issue by kilasuit** [DarqueWarrior/vsteam#130]
Steps to reproduce
------------------

```powershell
Install-Module MicrosoftTeams

Install-Module VSTeam
```

Expected behavior
-----------------

```none
No error
```

Actual behavior
---------------
![image](https://user-images.githubusercontent.com/6355225/52168158-85df0b00-271e-11e9-8c14-1bc880ed074f.png)

Environment data
----------------

```powershell
> Get-VSTeamAPIVersion

```

```powershell
> $PSVersionTable

```

I can get around this with `Install-Module -Name VSTeam -Repository PSGallery -AllowClobber` but it seems that this is aliases that are causing the issue.

Could the Aliases be removed in a future version?

**Comment by DarqueWarrior** [comment]
Yes.  I did it originally for backward compatibility with the modules original release.

**Comment by DarqueWarrior** [comment]
In version 6.0 the aliases are not exported by default. If you want to use the old aliases you can now run Set-VSTeamAlias.
