### ISSUE TITLE
[Feature] Have Build pipeline build a singel file PSM1 for importing

### ISSUE THREAD

**Issue by kilasuit** [DarqueWarrior/vsteam#132]
Whilst briefly looking at the issue within #109 there is a likelyhood that the way the module is being imported on some system is causing the issue with the classes being used.

Therefore as a potential fix I would suggest looking at trying to implement a pipeline that perhaps makes use of this module to build a unified PSM1 for distribution - https://github.com/PoshCode/ModuleBuilder/

**Comment by DarqueWarrior** [comment]
Thanks for the suggestion. I will review the module and see what it would take to convert VSTeam to use it.

**Comment by DarqueWarrior** [comment]
Working on this change now. Will be in version 6.0.

**Comment by DarqueWarrior** [comment]
Thanks again for this suggestion it appears to have fixed the other issues.
