### ISSUE TITLE
Consider changing Add-VSTeamAccount to Set-VSTeamAccount

### ISSUE THREAD

**Issue by paulomorgado** [DarqueWarrior/vsteam#133]
According to [PowerShell documentation on verbs](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands  "Approved Verbs for PowerShell Commands
"), **Add** "Adds a resource to a container, or attaches an item to another item" while **Set** "Replaces data on an existing resource or creates a resource that contains some data".

I think this is more a **Set** than an **Add**.

**Comment by DarqueWarrior** [comment]
Willl be changed in version 6.

**Comment by paulomorgado** [comment]
Need an extra pair of hands on that?

**Comment by DarqueWarrior** [comment]
You can take a peek at the SEP branch, The changes are complete just seeing if there are other issues I can close in this release.

**Comment by paulomorgado** [comment]
I don't see the SEP branch but I see you made the change in the master branch and published 6.0.0.

The documentation, however, still mentions `Add-VSTeamAccount`.

And, for backwards compatibility, maybe a `Add-VSTeamAccount` alias should be added.

**Comment by DarqueWarrior** [comment]
I just updated the help. Changing the version from 5 to 6 is because their are breaking changes. That name change was one that I mention in the changelog (now ;)).
