### ISSUE TITLE
Consider changing Add-VSTeamAccount's parameter PAT to SecurePersonalAccessToken

### ISSUE THREAD

**Issue by paulomorgado** [DarqueWarrior/vsteam#134]
Just because I'm picky. 😄

**Comment by DarqueWarrior** [comment]
There is a secure string (PAT) as well. Simply use the first version or leave the value off and be promoted for the secure value.

```
Add-VSTeamAccount [-Account] <String> [-Version] <String> -PAT <SecureString> [-Level <String>] [-UseBearerToken] [-Drive <String>] [<CommonParameters>]

Add-VSTeamAccount [-Account] <String> [-PersonalAccessToken] <String> [-Version] <String> [-Level <String>] [-UseBearerToken] [-Drive <String>] [<CommonParameters>]

Add-VSTeamAccount [-Account] <String> [-Version] <String> [-Level <String>] [-UseWindowsAuthentication] [-Drive <String>] [<CommonParameters>]

Add-VSTeamAccount -Profile <String> [-Drive <String>] [<CommonParameters>]
```

**Comment by paulomorgado** [comment]
I meant changing the name.

**Comment by DarqueWarrior** [comment]
Ah.  I missed that. I don't think I have a problem with that. There are a ton of breaking changes in 6.0.

**Comment by DarqueWarrior** [comment]
SMH looking at the code the parameter was already SecurePersonalAccessToken. It was just the help that was wrong. I updated the help and added an alias for PAT.

**Comment by paulomorgado** [comment]
For consistency, `Add-VSTeamProfile` should also have a `PAT` alias. And the documentation still mentions `PAT`.

**Comment by DarqueWarrior** [comment]
Thanks for letting me know the docs folder was not being updated. I just corrected the docs folder.
