### ISSUE TITLE
[Feature] Linking between results of Get-VSTeamBuild and Get-VSTeamRelease

### ISSUE THREAD

**Issue by dossen** [DarqueWarrior/vsteam#136]
In the web interface, it is possible to navigate from a Build to the Releases, that deploy that build, and from a Release to the Build it deploys.
It would be nice, if the results of Get-VSTeamBuild included a list of ReleaseIds or something like that on each and the result of Get-VSTeamRelease then had a BuildId on each item.

I'm unsure if it is possible to get this information by requesting additional Properties, but at the very least it could be more clear how to get from one item to the other and vice versa.

This would significantly improve on one of my current use cases for VSTeam - seeing how my builds and CI-pipeline is doing. Currently I'm looking at strings to hook objects together where releases are auto-triggered. Where the releases are created manually (production deployment) I currently cannot make the link.

**Comment by DarqueWarrior** [comment]
I did some research and found how to get the releases from a build id. You can do it today with VSTeam using the Invoke-VSTeamRequest like this.

```PowerShell
Invoke-VSTeamRequest -Url 'https://vsrm.dev.azure.com/loecda/Team Modul
e/_apis/release/releases/?api-version=5.0&artifactTypeId=Build&artifactVersionId=1346'
```

I figured that out from AzD REST API Docs on docs.com [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/list?view=azure-devops-rest-5.0).

There might be something similar you can do the same with builds.

**Comment by Alexlofern** [comment]
I do that using artifact id from the build def, something like that:

$RawBuildDef = Get-VSTeamBuildDefinition -ProjectName $Project -Id $BuildDef.Id -Raw -ErrorAction SilentlyContinue
$ArtefactId = $RawBuildDef.project.id + ":" + $BuildDef.Id
$RelDef = (Get-VSTeamReleaseDefinition -ProjectName $Project -Expand Artifacts | Where-Object Artifacts -Match $ArtefactId).Name

**Comment by SebastianSchuetze** [comment]
Thanks for the idea @Alexlofern and @dossen. This module is merely a wrapper for the API. Adding higher abstraction to add value to the module is not the scope of this module. But we have plans to make use of this. I am adding an extra label to not loose this idea!
