### ISSUE TITLE
Add-* vs New-*

### ISSUE THREAD

**Issue by MichelZ** [DarqueWarrior/vsteam#139]
I wonder if this is something that was just not thought about (i doubt it :) ), or if there is a specific reason that there are no "New-*" commands.

To me it feels odd to use these as "Add", because many of them are really creating new resources.

e.g. New-VSTeamGitRepository vs Add-VSTeamGitRepository
New-VSTeam vs Add-VSTeam
New-VSTeamProject vs Add-VSTeamProject

It just feels more "the powershell way" by using New-* instead of Add-* for many things.

Add- for me would be something like:
Add-VSTeamGroupMember    

Just a thought, thanks for the consideration and keep up the good work 👍

**Comment by DarqueWarrior** [comment]
If you review the PowerShell Verb guidelines Add is paired with Remove. Delete is not an approved verb. So after I New something how do I delete it? Given the approved Verbs Add and Remove were selected. https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands

**Comment by DarqueWarrior** [comment]
You can always add your own alias for the functions if you like.

**Comment by MichelZ** [comment]
Thanks for the explanation, and I'll go with the alias.

However I'd also like to submit some statistics from my system:
(Fairly standard, more or less just AzureRM PS installed):

New/Remove pairs: 421
Add/Remove pairs: 152

Or just for AzureRM modules:
New/Remove pairs: 282
Add/Remove pairs: 75

So while technically the guide does state "Add/Remove" pairs, it is used far more for New/Remove pairs, even by Microsoft itself... ;)

**Comment by DarqueWarrior** [comment]
Thanks for the data. The guidelines should be updated to reflect your findings.

**Comment by DarqueWarrior** [comment]
Maybe in a future release that has a lot of breaking changes I might swap them.

**Comment by MichelZ** [comment]
Cool.
Yes, I‘ll open an issue with the ps docs team.
