### ISSUE TITLE
How can I update repository permissions through Posh and the VSTeam module?

### ISSUE THREAD

**Issue by jakobjs** [DarqueWarrior/vsteam#146]
Hi all,

How can I change Git repository default permissions for all repos through Posh and the VSTeam module? It is outlined here but there is no automation documentation or reference:

https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-git-tfvc-repository-permissions?view=azure-devops

I want all Contributors to have the "Edit Policies" permissions by default and I use a posh script to create all TFS projects..

https://imgur.com/a/BIrywws

Environment data
----------------

```powershell
> Get-VSTeamAPIVersion

Name                           Value
----                           -----
ServiceFabricEndpoint
Build                          3.0
ExtensionsManagement           3.0-preview
Release                        3.0-preview
Version                        TFS2017
MemberEntitlementManagement
Packaging
Tfvc                           3.0
Git                            3.0
Core                           3.0
Graph
DistributedTask                3.0-preview
```

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.407
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.407
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jakobjs** [comment]
@DarqueWarrior Any ideas on how to do this?

**Comment by jakobjs** [comment]
Oops, did not mean to close this.

**Comment by MichelZ** [comment]
@jakobjs this is currently only possible using Invoke-VSTeamRequest.
I am working on support for this, and it is a work in progress. See PR here: #144

**Comment by MichelZ** [comment]
Oh, I see TFS. I think Microsoft has not yet released all the necessary API's to do this properly in TFS

**Comment by jakobjs** [comment]
So, only possible via Azure DevOps and Azure DevOps Server? OK. Will follow your request #144 👍

**Comment by MichelZ** [comment]
Only Azure DevOps Service actually, not Server. Many API's that I need seem to be online-only currently (all the Graph stuff)
