### ISSUE TITLE
Get-VSTeamBuildArtifact fails

### ISSUE THREAD

**Issue by apobekiaris** [DarqueWarrior/vsteam#148]
Hi

I am executing the next script 

```ps1
$build = (Get-VSTeamBuild -ProjectName eXpandFramework|Where-Object {$_.DefinitionName -like "Xpand-Lab" -and $_.Result -eq "succeeded"}|Select-Object -First 1)
Get-VSTeamBuildArtifact -ProjectName eXpandFramework -Id $build.id 
```

however there is an exception in the output
```
The property 'properties' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\6.1.0\Private\applyTypes.ps1:93 char:7
+       $item.resource.properties.PSObject.TypeNames.Insert(0, 'Team.Bu ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict


id   : 232
name : Xpand.v18.2.601.10


id   : 233
name : build.SourceLabel
```

and is still not clear how do I download the artifacts.

**Comment by DarqueWarrior** [comment]
I think this has to do with upgrading the version of the API we use by default. I have noticed some properties have moved around. I will look into it now.

**Comment by DarqueWarrior** [comment]
Please run the following command and report the results.

```PowerShell
Get-VSTeamAPIVersion
```

**Comment by apobekiaris** [comment]
```
Name                           Value
----                           -----
ServiceFabricEndpoint
Build                          3.0
ExtensionsManagement           3.0-preview
Release                        3.0-preview
Version                        TFS2017
MemberEntitlementManagement
Packaging
Tfvc                           3.0
Git                            3.0
Core                           3.0
Graph
DistributedTask                3.0-preview
```

**Comment by apobekiaris** [comment]
@DarqueWarrior any updates on this case?

looks like if I ErrorAction Continue I get a valid download Url

**Comment by DarqueWarrior** [comment]
Are you connected to a TFS2017 server?

**Comment by apobekiaris** [comment]
i try to download artifact from a Azure DevOps Hosted Agent pipeline, checking the pipeline setup it looks like it throws if the pipeline uses the [Publish PipeLine Artifacts task](https://docs.microsoft.com/el-gr/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops&viewFallbackFrom=vsts) instead when I used the [Publish build artifact task](https://docs.microsoft.com/el-gr/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops) I was able to get a valid DownloadUrl. For me this solution is fine, thanks for the support.

**Comment by DarqueWarrior** [comment]
The reason I asked is because the version of the API you were using was for TFS2017. Call SetVSTeamAPIVersion and set to AzD and try again.

**Comment by markwragg** [comment]
I've raised a PR that should fix this issue:

https://github.com/DarqueWarrior/vsteam/pull/232

It occurs because the API is returning an extra result after all the artifact that is a different type (its called GitRef) and doesn't have a sub property named "properties":

![image](https://user-images.githubusercontent.com/6706196/72984998-e3abad80-3ddc-11ea-8088-dfffe53cb4ef.png)

My PR adds an extra condition to the `if` statement that ignores results from the API that don't have a .properties property.
