### ISSUE TITLE
[Suggestion] Get Timeline of a Build

### ISSUE THREAD

**Issue by SebastianSchuetze** [DarqueWarrior/vsteam#150]
I was recently making some tests with Azure Pipeline with Pipeline Artifacts vs Build Artifacts. With that I needed to get the timeline of around 400 builds I triggered. I saw this functionality is missing. Basically it would call the following API method:

https://docs.microsoft.com/en-us/rest/api/azure/devops/build/timeline/get?view=azure-devops-rest-5.0

I could try to include it myself and make a PR, but I have some questions:

- Should it be an extra command?
- Should it be uncluded as a property with Get-VSTeamBuild?
- Do I need to create an object with format files or just return the JSON object?

**Comment by DarqueWarrior** [comment]
Sorry for the delay. Let me review the current code and get back to you.

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior any news on my questions? I am aware that you are busy! :-)

**Comment by DarqueWarrior** [comment]
- I would call it Get-VSTeamBuildTimeline
- I don't think it needs to be in the build object
- You don't have to create an object but you should have format files.

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior a quick side question: When is it appropriate to create objects for data returned?

**Comment by SebastianSchuetze** [comment]
I [added the function](https://github.com/RazorSPoint/vsteam/blob/topic/Get-VSTeamBuildTimeline/Source/Public/Get-VSTeamBuildTimeline.ps1) and it seems to work basically, but there is a problem. it seems like that the planId and changeId parameters do not seem to have any effect on the API. But I am also not sure what they would do in certain scenarios.
If I give a "fake" id in one of those, the API returns the same results when leaving them out.

Also when you have a timeline the records are pretty much unsorted and they have a hierarchie, but are ordered in a flat list.

I have a public project, where you have an example:
https://dev.azure.com/razorspoint-test/Pipeline%20Artifacts%20vs%20Build%20Artifacts/_apis/build/builds/574/timeline?api-version=5.0

https://dev.azure.com/razorspoint-test/Pipeline%20Artifacts%20vs%20Build%20Artifacts/_build/results?buildId=574

I used this project to test the performance of build agents with "build artifacts" versus "pipeline artifacts". To get a better overview of the pipeline, I converted the flat timeline array into a tree of arrays (like in [my following gist](https://gist.github.com/SebastianSchuetze/83b7320b77e829b0164af776d0b939e6#file-get-azuredevopsbuildtimelines-ps1-L9)).
Would you like to have the option to return it as a tree? And if yes, should I define this as a nested function?

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior do you have any idea about the problem in my previous post?

**Comment by DarqueWarrior** [comment]
Hey @willsmythe can you help here?

**Comment by MichelZ** [comment]
@SebastianSchuetze Just leave the plan id out if you don't know what it's doing, and PR this.
Issue has been open for a while now :)

**Comment by MichelZ** [comment]
Also, make sure BuildID and ProjectID/Name are mandatory

**Comment by SebastianSchuetze** [comment]
This has been merged into master and will be out with the next release.
