### ISSUE TITLE
[Feature] Would be great to have a Get-VSTeamIterations to allow to pull all known iterations for the project.

### ISSUE THREAD

**Issue by PHaigh-tw** [DarqueWarrior/vsteam#152]
Managing iterations in the Azure DevOps project would be incredibly useful, both Add, Get and Remove to allow control of iterations prior to creating WorkItems.

We're trying to automate the iterations and use DocFx to create automated documentation from our sprint iterations along the way.

Thanks!

**Comment by DarqueWarrior** [comment]
You can do that now with the Invoke-VSTeamRequest function now like this:

```powershell
ivr -Url 'https://dev.azure.com/{organization}/{project}/{team}/_apis/work/teamsettings/iterations' | select -ExpandProperty value
```

**Comment by MichelZ** [comment]
I need this, too, and might do some work in this direction once my first PR is through and I know the quality of my code is up to the project :)

**Comment by MichelZ** [comment]
Oh, and actually, in my PR you can already GET them. They are actually called "Classification Nodes".
```

PS Z:\> Get-VSTeamClassificationNode -ProjectName "mizetest" -StructureGroup iterations

ID Identifier                           Name     Path                StructureType HasChildren
-- ----------                           ----     ----                ------------- -----------
46 6538ab2e-7ff9-4866-92bf-6d94d515a331 mizetest \mizetest\Iteration iteration     True       

```

#144

**Comment by SebastianSchuetze** [comment]
@PHaigh-tw and @MichelZ this has been added with the last PR #286 and will be available with the next release.
