### ISSUE TITLE
[Feature] Extend Get-VSTeamPullRequest to return X PR's or All PR's

### ISSUE THREAD

**Issue by kilasuit** [DarqueWarrior/vsteam#154]
Ideally I would like to use PowerShell to get all PR's in a project in a single object that I can use for exporting history reasons.

Currently Get-VSTeamPullRequest will bring back only open PR's unless you provide an ID.

However it would be useful to do the following
```
Get-VSTeamPullRequest -All
```
or
```
Get-VSTeamPullRequest -Last 50
```

**Comment by MichelZ** [comment]
Should be easy to do, there is a searchCriteria.status which can be set to all (defaullt: active)

Will take a stab at it tomorrow if I don‘t forget 🙄
