### ISSUE TITLE
Get-VSTeamBuildDefinition fails

### ISSUE THREAD

**Issue by botterberg** [DarqueWarrior/vsteam#155]
Steps to reproduce
------------------

`Get-VSTeamBuildDefinition -Project my-project'

Get the following error

`The property 'variables' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\6.2.0\Classes\VSTeamBuildDefinition.ps1:35 char:7
+       $this.Variables = $obj.variables
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

The property 'variables' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\6.2.0\Classes\VSTeamBuildDefinition.ps1:35 char:7
+       $this.Variables = $obj.variables
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict`
----------------

VSTeamVersionTable
`ServiceFabricEndpoint                   5.0-preview
Build                                               5.0
ExtensionsManagement                  5.1-preview
Release                                            5.1-preview
Version                                             VSTS
MemberEntitlementManagement    5.1-preview
Packaging                                         5.1-preview
Tfvc                                                   5.0
Git                                                     5.1-preview
Core                                                  5.0
Graph                                                5.1-preview
DistributedTask                                 5.0-preview`

PSVersionTable
`PSVersion                                5.1.17134.590
PSEdition                                 Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                           10.0.17134.590
CLRVersion                              4.0.30319.42000
WSManStackVersion               3.0
PSRemotingProtocolVersion   2.3
SerializationVersion                 1.1.0.1`

**Comment by danstur** [comment]
The issue seems to stem from `VSTeamBuildDefinition.ps1` that has the following comment:
```
# This is only in VSTS. In TFS it is a build property
      if ($obj.PSObject.Properties.Match('process').count -gt 0) {
         $this.Process = [VSTeamBuildDefinitionProcess]::new($obj.process, $Projectname)
      }
```

With Azure DevOps server (on-premise) the property also exists, which means we go down this branch. In the VSTeamBuildDefinitionProcess.ps1 the object type is equal to 1 which means the phases are created and that's the problem since there's no condition on the object. 

A quick fix is to check that `$obj.condition` exists before assigning it and otherwise leaving it null.

**Comment by DarqueWarrior** [comment]
Are you connecting to TFS or AzD?  If TFS or AzD Server what version?

**Comment by DarqueWarrior** [comment]
Need a little more details. I just tested version 6.2.1 with TFS 2017, TFS 2018 and AzD. All worked.

**Comment by RPhay** [comment]
I've encountered this as well running over hundreds of build definitions in our Azure DevOps projects.  The workaround is simply to wrap the line in a quick check at line 35:

      if ( $obj.PSObject.Properties.name -match 'Variables' ) {
         $this.Variables = $obj.variables
      }

**Comment by botterberg** [comment]
I was running against Azure DevOps.
