### ISSUE TITLE
[Feature] Extent Add-VSTeamWorkItem to set Tag

### ISSUE THREAD

**Issue by christiantippner** [DarqueWarrior/vsteam#164]
i would like to add the tag property on a workitem. It would be usefull to set it like:

`Add-VSTeamWorkItem -Title "New Work Item" -WorkItemType Task -Tag "MyTag"`

**Comment by DarqueWarrior** [comment]
Doing a quick search of the [API](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items?view=azure-devops-rest-5.0) I don't see a documented way to add a tag to a work item.

**Comment by christiantippner** [comment]
On update workitem [documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/update?view=azure-devops-rest-5.0#add_a_tag) is described , how to add tag. 

**Add a tag**
***Sample Request***

`PATCH https://dev.azure.com/fabrikam/_apis/wit/workitems/{id}?api-version=5.0`
***Request Body***

`[
  {
    "op": "test",
    "path": "/rev",
    "value": 6
  },
  {
    "op": "add",
    "path": "/fields/System.Tags",
    "value": "Tag1; Tag2"
  }
]`

**Comment by SebastianSchuetze** [comment]
@christiantippner and @DarqueWarrior there has been an update which allows you to set the tags for Update and Add WorkItem commands. So maybe this one could be closed?

I already connected the issue with this one and the pull request for this was #190 .
