### ISSUE TITLE
[feature] Extend `Get-VSTeamReleaseDefinition` to expand Task Groups

### ISSUE THREAD

**Issue by Rincey** [DarqueWarrior/vsteam#168]
Hi @DarqueWarrior 
When executing a `Get-VSTeamReleaseDefinition` I can expand the returned object down to tasks. But if the task is a task group (`definitionType   : metaTask`), I cannot expand it any further.
The API appears to be there on the [API documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/taskgroups/list?view=azure-devops-rest-5.0) page.

It would be very handy to be able to expand the task groups out into their component tasks.

Many thanks.

**Comment by DarqueWarrior** [comment]
Are you interested in giving this a shot and issuing a PR for the API? There should be patterns you can follow from other APIs others have wrapped already.

I would also look at the Invoke-VSTeamRequest function. You can use that to call any API in AzD even if we have not wrapped it yet.

**Comment by SebastianSchuetze** [comment]
Thanks for the idea @Rincey . This module is merely a wrapper for the API. Adding higher abstraction to add value to the module is not the scope of this module. But we have plans to make use of this. I am adding an extra label to not lose this idea!
