### ISSUE TITLE
Security Report

### ISSUE THREAD

**Issue by g-pearl** [DarqueWarrior/vsteam#174]
I have been tasked with creating a security report for TFS and I am hoping that this module can help.

I have set my account using the 
Set-VSTeamAccount -Account http://xxxxxxx:8080/tfs -UseWindowsAuthentication

but after that all the commands do not return anything or even tab complete produces a (404) no Found error.  

I am sure that this is something I am doing wrong but not exactly sure where to go next.

Server is an on-premise visual studio 2017.

I assume once I am connected I will use the get-vsteamaccesscontrollist cmdlet - am I correct?

Thanks in advance for your help.

**Comment by DarqueWarrior** [comment]
I am afraid the Get-VSTeamAccessControlList is only supported on Azure DevOps Service (online).

Someone would have to find the correct API to call for TFS2017.  If you do find it you can use the Invoke-VSTeamRequest function to make calling the API easier. 

As for your issues using the module are you logged into Windows with the same username and password you log into TFS with? If not the -UserWindowsAuthentication is not going to work. You can also log into TFS and create a Personal Access Token to use with VSTeam.
