### ISSUE TITLE
List all work items

### ISSUE THREAD

**Issue by Tiberriver256** [DarqueWarrior/vsteam#175]
I think it would be awesome if there was a way to list all work items easily. I see the commands to get and show a work item by id but I'm not sure how to find that Id.

It could be as simple as calling the query endpoint with wiql to fetch all work items. The other option would be to have a cmdlet where you could pass wiql direct and fetch work items that way.

**Comment by SebastianSchuetze** [comment]
Hi @Tiberriver256 

it is some time ago, but from your perspective how would you see this cmdlet regarding to parameters?

I see the following possibilities:
1. fill in the full custom wiql query
2. only give project & team and give all (or top=X) work items back from that team
3. give the option to expand the id to full work items

What do you think @DarqueWarrior especially for number 3. Should the work items be automatically expanded? This should then be done by the cmdlet itself. Unless there is an API option.

A basic call with VSTeam work with this example already:
```powershell
Set-VSTeamAccount -Profile <organization name>

$apiWorkItemUrl = "https://dev.azure.com/<organziation name>/<project>/<team name>/_apis/wit/wiql?api-version=5.1"

[array]$requestlist = @();

$request = @{ query = "Select [System.Id], [System.Title], [System.State] From WorkItems"}

$jsonString = ConvertTo-Json -Depth 50 -inputobject $request

$items = Invoke-VSTeamRequest -method POST -Url $apiWorkItemUrl -ContentType 'application/json' -body $jsonString
```

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior I am currently checking how to implement this.

The API requires you to give the project, team, resource (wit) and area (wiql). However, the function _callApi and [_buildRequestURI](https://github.com/DarqueWarrior/vsteam/blob/8341a1ccce8a947bd4366f20f095f1df5a51b204/Source/Private/common.ps1#L65) do not allow me to add a team so it can be reflected in the URL.

I could use the Invoke-VSTeamRequest, but that would be a different implementation from the rest. Do you have an idea of how I should proceed?

**Comment by ferwe** [comment]
I solve it this way until it works with the command:
$ids = 1..200
$AZWorkItems = Get-VSTeamWorkItem -ids $ids -ErrorPolicy Omit

Unfortunately it adds empty items for each number between the highest number of WorkItems and the choosen range.

**Comment by ferwe** [comment]
@SebastianSchuetze 
Check this module. With this module, you are able to get all items by a filter.
https://github.com/igoravl/TfsCmdlets
for example:
Get-TfsWorkItem -Filter '[System.WorkItemType] = "Bug"'

**Comment by SebastianSchuetze** [comment]
Thanks!
I am using the same API approach as this cmdlet, although with different parameters. It uses basically WIQL in the API. 
If you look at the linked PR you will see that it uses the same approach.
But I will have a look if that can be improved somehow.

**Comment by ferwe** [comment]
I had a look at your PR
Looks good!
Thanks for your work :)

**Comment by SebastianSchuetze** [comment]
@Tiberriver256 @ferwe the PR was just merged some hours ago. So for the next release the requested feature should be possible then.

**Comment by SebastianSchuetze** [comment]
@DarqueWarrior can you close it if the creator is not closing it?

**Comment by DarqueWarrior** [comment]
Creating merging the changes for the PR now.
