### ISSUE TITLE
Create a AzDO Demo zip

### ISSUE THREAD

**Issue by Seekatar** [DarqueWarrior/vsteam#180]
Have you blogged or documented the build/deploy pipeline for this repo?  It looks like it'd be a great model for writing PS modules.  Would you consider creating a zip using the AzDo Demo Generator?  

https://azuredevopsdemogenerator.azurewebsites.net/?enableextractor=true

Then adding it to this repo perhaps?

**Comment by DarqueWarrior** [comment]
I am going to update [Yo Team](https://www.npmjs.com/package/generator-team) to use this pattern. I was just testing the pattern with this module. Once in Yo Team you will be able to create full projects with Azure DevOps pipelines.
