### ISSUE TITLE
[Feature] Update-VsTeamWorkItem to add a tag

### ISSUE THREAD

**Issue by joeywas** [DarqueWarrior/vsteam#183]
Feature request: Update-VsTeamWorkItem to add a tag to a workitem. 

I envision it would work something like this:

Update-VsTeamWorkItem -Id 1 -Tag TestTag1

Note: I removed the array (multiple) tags, as that's more complex than I am comfortable with doing.

**Comment by SebastianSchuetze** [comment]
@joeywas regarding your PR, this issue can be closed, right? Hope you are not too frustrated that you made effort for your change. But I am happy that the current solution works for you. Version is already published and should work for you.

**Comment by joeywas** [comment]
Yes, it can be closed. Not frustrated, i am still fairly new to
collavorating on github so it's good learning experience!
Joseph
