### ISSUE TITLE
[Feature] Update-VsTeamWorkItem to modify State field

### ISSUE THREAD

**Issue by joeywas** [DarqueWarrior/vsteam#184]
To adjust the state of an existing work item, the -State parameter on Update-VsTeamWorkItem would allow setting the State of work item. If an invalid state is passed in, an exception should be returned.

Example:
`Update-VsTeamWorkItem -Id 1 -State Resolved`

**Comment by SebastianSchuetze** [comment]
@joeywas do you think the current solution from #190 would accommodate your suggestion sufficiently?

**Comment by joeywas** [comment]
Yes sir!
