### ISSUE TITLE
[Improvement] Improve Pipelines with CredScan

### ISSUE THREAD

**Issue by SebastianSchuetze** [DarqueWarrior/vsteam#185]
Hi,

I  am currently testing the Microsoft Security Code Analysis, which is in private preview with Microsoft. I ran it on your repository and found some issues with CredScan.
This one tries to find passwords in your repository. 

This one has found 8 issues and I am only posting it here because I checked them all and those where only no real passwords and mostly for the unit tests:

![image](https://user-images.githubusercontent.com/7256168/63196490-b1e82b00-c075-11e9-834c-bb3d3f4e2b5d.png)

Nevertheless, I would like to suggest to implement CredScan to you yaml pipeline and also add a ignore file to it.

I already created it but would like to first align with you, because you would need to install it on you AzD instance first. It is not publically on the marketplace yet, but I am sure it would be no problem for you to use it. I am sure it could be valuable.

**Comment by SebastianSchuetze** [comment]
I added the pull request to show what I meant. I hope that this was okay. Of course, the PR fails, since these tasks are not installed on your organization.

**Comment by DarqueWarrior** [comment]
Do you know who to contact to have the extension shared with the LoECDA org?

**Comment by SebastianSchuetze** [comment]
Yes, initially I signed up at the following page: https://secdevtools.azurewebsites.net/
And the mail given on that page comes when clicking "Sign Up". Never had a direct name, the signature had only "Microsoft SCA Team".

**Comment by DarqueWarrior** [comment]
Closed with pr #186
