### ISSUE TITLE
[Feature] Update-VsTeamWorkItem and Add-VsTeamWorkItem to add any value for a work item type

### ISSUE THREAD

**Issue by SebastianSchuetze** [DarqueWarrior/vsteam#188]
I want to suggest the following feature to adjust update and add workitem cmdlets.

1. Add a parameter of type `hashtable` with the name AdditionallFields
2. The parameter itself will be initialized and forwarded like the example below
```powershell
$workItemFields = @{
         "System.Tags" = "MyTag1;MyTag2"; 
         "System.AreaPath" = "ProjectPath\\Area";
         "CustomProcess.CustomField" = "CustomFieldValue"
}

Add-VSTeamWorkItem -ProjectName "MyProject" -Title "NEw WorkItem" -WorkItemType "Task"-Description "My Description" -AdditionalFields $workItemFields
```
3. The hashtable will be iterated and added with the same syntax as already done with the title, description and so on.
4. additionally it will be checked, that to fields are defined in the hashtable that already have been given with the other parameters.

This would give the possibility to add any field. There is a disadvantage for a bit more complex fields like "relations", since it could still be used, but would need to be manually correctly initialized with the hash table. But it would certainly give the freedom to easily add all the other fields.

**Comment by SebastianSchuetze** [comment]
This correlates with #183, #187 and #164 if this would be an accepted way, then it would solve these as well as future requests for adding field X to a work item.

**Comment by DarqueWarrior** [comment]
Reviewing PR now. Thanks for all the support.

**Comment by SebastianSchuetze** [comment]
I am closing the issue since it has been merged and published.
