### ISSUE TITLE
[Improvement] How to refactor cmdlets that have redundant code

### ISSUE THREAD

**Issue by SebastianSchuetze** [DarqueWarrior/vsteam#189]
@DarqueWarrior I have been looking at some cmdlets and I think some of them have duplicate code. Especially the ones that have "Add" and "Update" cmdlets using the same object.

Is there a place where I can refactor them to one method? I saw the common.ps1 but they seem to be more for global common function and not just for one or two.

Any suggestion where to put those?

**Comment by DarqueWarrior** [comment]
common.ps1 is for global constants. For API specific I would place a file in the private folder. Create a file that omits the verb sense it may cover several. For example for Add-VSTeamWorkItem and Update-VSTeamWorkItem create a file in private called VSTeamWorkItem.ps1. That file can contain any common functions for VSTeamWorkItem functions.
