### ISSUE TITLE
[Suggestion]Function Naming

### ISSUE THREAD

**Issue by mortenlerudjordet** [DarqueWarrior/vsteam#19]
Just a personal preference, though I wanted to raise it here.
Please consider using the following naming convention for your functions (or similar)

 Verb-(ModuleName)(Function)

Example:
Add-TeamBuild
New-TeamBuild
Add-TeamBuildDefinition
Get-TeamRelease
...
This will help mitigate conflicting functions from other modules, and making it more consistent

Thanks for the module

**Comment by DarqueWarrior** [comment]
Thanks for the feedback. Which other module is it conflicting with?

**Comment by mortenlerudjordet** [comment]
Should have said : reduce the likelihood of encountering conflicting function names found in other modules.
I was trying out Adam's VSTS module at the same time, luckily he used Get-vstsBuild instead of Get-Build. So I have no actual conflicting modules at this time.

**Comment by DarqueWarrior** [comment]
This is very timely. I just got off a 1 hour call on the naming of my module. So I will change it. I am going to change the module name and the noun prefix.  Any suggestions?

**Comment by mortenlerudjordet** [comment]
Cool!
How about:
PSTS = Powershell Team Services
TSPS
vsTeamS
PSTeamS

Just to get you started

**Comment by PlagueHO** [comment]
Great module @DarqueWarrior - impressive feature set and thank you for creating it.

The name of the module itself might cause some confusion though. I assumed this would have something to do with Microsoft Teams - not VSTS/TFS.

**Comment by DarqueWarrior** [comment]
The PowerShell team is all over me to change it. :)  The change is coming just have to settle on a new name and noun.  @mortenlerudjordet  has some good suggestions. I will decide soon.

**Comment by DarqueWarrior** [comment]
We went with VSTeam. But the entire module was renamed and VSTeam noun put in place.
