### ISSUE TITLE
Need Remove-AzureRMServiceEndpoint

### ISSUE THREAD

**Issue by mrichman** [DarqueWarrior/vsteam#20]
The function `Remove-AzureRMServiceEndpoint` would come in handy, and it's missing from the module.

Presumably, any `Add-*` should have a corresponding `Remove-*`.

**Comment by DarqueWarrior** [comment]
I will add a Remove-AzureRMServiceEndpoint alias that maps to Remove-VSTeamServiceEndpoint.
