### ISSUE TITLE
ServiceEndPoint details

### ISSUE THREAD

**Issue by apobekiaris** [DarqueWarrior/vsteam#201]
I have declare a Nuget Service connection and I would like to use to feed the credentials in script for example for

dotnet nuget push

is there a way to it?

**Comment by DarqueWarrior** [comment]
You want to be able to get the creds from an existing service endpoint for use in PowerShell script?

**Comment by apobekiaris** [comment]
yes

**Comment by SebastianSchuetze** [comment]
@apobekiaris do you want to use it in an Azure DevOps pipeline or somewhere outside of the pipeline?

There are possibilities to access service connections within a pipeline (like other pipeline tasks), but the point for using service connections is, that nobody can just access them.
I think the later will not be possible.

**Comment by DevExpress-XAF** [comment]
if I could access my service connections and connect through them I do not have to use Secrets which are not safe for pull requests

**Comment by SebastianSchuetze** [comment]
The question is where do you want to use them? In Azure Pipelines or somewhere outside of the pipelines.

**Comment by apobekiaris** [comment]
yes in Azure as I said I know use secrets to retrieve the same credentials that are used from my connections.

**Comment by MichelZ** [comment]
There is no way doing this with this project here unfortunately.
I‘d close this isse @DarqueWarrior @SebastianSchuetze

**Comment by SebastianSchuetze** [comment]
I also didn't see any solution or possibility! So closing this for now.
