### ISSUE TITLE
Disable/Enable-VSTeamAgent results in unusable agent due to maxParallelism reset to 0

### ISSUE THREAD

**Issue by japj** [DarqueWarrior/vsteam#203]
Steps to reproduce
------------------

```powershell
Disable-VSTeamAgent -poolId xx -Id yy
Enable-VSTeamAgent -poolId xx -Id yy
```
Queue a build to this specific agent

Expected behavior
-----------------
- the agent to start building

Actual behavior
---------------
- the agent seems to be "stuck" and is not picking up any build anymore
- reboot does not help
- disable/enable through web interface does not help
- reinstalling agent does "fix" it

After searching for a while we discovered that it seems the `maxParallelism` is reset to `0` while using Disable/Enable-VSTeamAgent. 

As described on https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/agents/update?view=azure-devops-rest-5.1#request-body `maxParallelism` is "Maximum job parallelism allowed for this agent.".

I don't know why it resets to `0`, but adding 'maxParallelism':1 to Disable/Enable-VSTeamAgent.ps1 did solve the issue, but i am wondering if anyone else is seeing this same behaviour?

Environment data
----------------

OS
- Windows

Server

- Azure DevOps Server RTM

```powershell
> Get-VSTeamAPIVersion
Name                           Value
----                           -----
Release                        3.0-preview
Version                        TFS2017
MemberEntitlementManagement
DistributedTask                3.0-preview
Core                           3.0
Packaging
ServiceFabricEndpoint
VariableGroups                 3.2-preview.1
Build                          3.0
Git                            3.0
ExtensionsManagement           3.0-preview
Graph
Tfvc                           3.0

```

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17134.858
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.858
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

@Geertvdc have you perhaps also seen this behavior on an Azure DevOps Server environment?

**Comment by DarqueWarrior** [comment]
Thank you so much for this. I will work on getting it merged now.
