### ISSUE TITLE
Feature Request: Cancel existing build

### ISSUE THREAD

**Issue by japj** [DarqueWarrior/vsteam#206]
Add support for cancelling an existing build.

This could be done by PATCHing the 'status' field to 'cancelling' in Update-VSTeamBuild (adding additional optional parameter).

Or by a seperate Cancel-VSTeamBuild

**Comment by SebastianSchuetze** [comment]
I could look into that. Suggested Cmdlet 

Stop-VSTeamBuild

Cancel is not an [approved verb](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands) for PowerShell. But Stop is a synonym for such an action.

**Comment by DarqueWarrior** [comment]
Stop-VSTeamBuild would be a good addition.

**Comment by SebastianSchuetze** [comment]
@japj and @DarqueWarrior this issue has been implemented and merged by @brittandeyoung.
