### ISSUE TITLE
Add-AzureRMServiceEndpoint does not verify ServicePrincipalKey

### ISSUE THREAD

**Issue by mrichman** [DarqueWarrior/vsteam#21]
When calling `Add-AzureRMServiceEndpoint` with an invalid parameter for `-servicePrincipalKey`, the function does not verify the connection.

I am able to create an endpoint in my on-prem TFS with a bad password, so the verification fails:

![image](https://user-images.githubusercontent.com/11228/30596799-3379cac0-9d23-11e7-8086-27f9565d20e5.png)

**Comment by DarqueWarrior** [comment]
I think this should be a switch on the function because even on the dialog you are not forced to verify the connection.  Something like ```Add-AzureRMServiceEndpoint -Verify```. Comments?

**Comment by mrichman** [comment]
How would the return code disambiguate failing to add the endpoint with failing to verify? Maybe it should be two different functions, i.e. `Verify-AzureRMServiceEndpoint` ?

**Comment by DarqueWarrior** [comment]
I will have to give that some thought. My knee jerk response is we define the error codes or it throws and exception if it could not verify.

**Comment by DarqueWarrior** [comment]
What do you think about using the -WhatIf for verify?

**Comment by mrichman** [comment]
I suppose that would be okay, so long as the behavior is documented.

**Comment by KaiWalter** [comment]
@mrichman + @DarqueWarrior : 
Sorry guys, I'm in clean up mood.
Can this issue be closed? I fail to comprehend where this issue relates to this project ```VSTeam```.

**Comment by mrichman** [comment]
Feel free to close. I no longer use TFS/VSTS.
