### ISSUE TITLE
Support for Organization policies

### ISSUE THREAD

**Issue by SebastianSchuetze** [DarqueWarrior/vsteam#215]
There is a not documented API, which is part of the public accessible API. This can handle the organization policies

There is already a feedback connected to it to have this officially public

https://developercommunity.visualstudio.com/content/idea/397816/no-rest-api-present-for-organization-settings-poli-1.html

There is also an issue explaining this API a bit more in detail:
https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/146

@DarqueWarrior do you think there is a better way to push it? Maybe we should [all vote on it](
https://developercommunity.visualstudio.com/content/idea/397816/no-rest-api-present-for-organization-settings-poli-1.html)!

I could implement it, even though it is not official, but it could still work properly

**Comment by DarqueWarrior** [comment]
This would not be the first time I had to resort to Fiddler and other methods to add calls to the module.  I am ok with adding undocumented methods. Lets make sure the help says that so people know they may run into issues given the API is undocumented.
