### ISSUE TITLE
How to remove orphan endpoints?

### ISSUE THREAD

**Issue by mrichman** [DarqueWarrior/vsteam#22]
I have a few "orphan" endpoints which were created with an older build of this module. I don't seem to be able to delete them through TFS, and there is no obvious way to do it via PowerShell.

![image](https://user-images.githubusercontent.com/11228/30596939-8b6bfe7e-9d23-11e7-8314-7fca6980ee57.png)

**Comment by DarqueWarrior** [comment]
I will ping PMs from the VSTS product team for help.

**Comment by RoopeshNair** [comment]
@mrichman, can you try updating it once and then attempt delete? let us know if you are still facing the issue

**Comment by mrichman** [comment]
@RoopeshNair I'm unable to update or disconnect:

![image](https://user-images.githubusercontent.com/11228/30762788-63b68e68-9fb1-11e7-9df9-7a94cafcf00b.png)

**Comment by RoopeshNair** [comment]
@Vincent A<mailto:vinca@microsoft.com> – can you please take a look?

[addTag:deployment;dri;v3]

**Comment by ObsidianPhoenix** [comment]
Have you tried using the `Remove-VSTeamServiceEndpoint` method in the module? Originally called `Remove-ServiceEndpoint` before the VSTeam rename.

**Comment by mrichman** [comment]
I just tried this:

`Remove-VSTeamServiceEndpoint -id 23dbd458-b3ce-40a0-8a77-47b9adc95486 -ProjectName Student -Verbose`

Where that GUID is the `resourceId` parameter in my TFS URL: `http://tfs:8080/tfs/EcoSys/Student/_admin/_services?resourceId=<xxxx>`

The command failed, but the output indicates success:

```
VERBOSE: DELETE
http://tfs:8080/tfs/EcoSys/Student/_apis/distributedtask/serviceendpoints/23dbd458-b3ce-40a0-8a77-47b9adc95486?api-version=3.0-preview.1 with 0-byte payload
VERBOSE: received -1-byte response of content type

Deleted service endpoint 23dbd458-b3ce-40a0-8a77-47b9adc95486
```

However, the endpoint still remains.

**Comment by ObsidianPhoenix** [comment]
Url looks good. In keeping with the [documentation](https://www.visualstudio.com/en-us/docs/integrate/api/endpoints/endpoints).

It would be interesting to try and see what the actual response code from that request is. It's supposed to be 204 by the looks of it.

Just to confirm, what version of TFS are you running? It appears that that version of the Api is only available from TFS 2017 onwards. But then again, if I try `Get-VSTeamServiceEndpoint` here (we're on 2015) I get the standard http error page spat out. I would expect the Remove to do likewise.

**Comment by mrichman** [comment]
@ObsidianPhoenix I'm running TFS 2017 RTM (15.105.25910.0).

The `-Verbose` flag doesn't indicate the HTTP response code.

**Comment by DarqueWarrior** [comment]
Hey @RoopeshNair has anyone from the PG had a chance to take a look at this?

**Comment by DarqueWarrior** [comment]
I just pinged the team again on this.

**Comment by niadak** [comment]
@mrichman, It will be great if we can have a Skype call to debug the issue. Can you please share your Skype Id with us if possible?

Can you please try to delete the endpoint via Rest API using PostMan or similar rest api tool? The url will be similar to
http://tfs:8080/tfs/EcoSys/Student/_apis/distributedtask/serviceendpoints/23dbd458-b3ce-40a0-8a77-47b9adc95486?api-version=3.0-preview.1
HTTP Method : Delete

Please post the response of the  rest call here in case  you get some error.

**Comment by mrichman** [comment]
@niadak Sure, but I'm not available this week for a Skype call. I can try the delete method and reporting my findings.

**Comment by mrichman** [comment]
@niadak Calling DELETE on that URL returns HTTP 204 (No content) with the following response headers:

```
ActivityId →f9deb713-e32e-4756-81b6-92ae66507e11
Cache-Control →no-cache
Date →Tue, 28 Nov 2017 16:22:19 GMT
Expires →-1
Lfs-Authenticate →NTLM
P3P →CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Persistent-Auth →true
Pragma →no-cache
Server →Microsoft-IIS/10.0
X-AspNet-Version →4.0.30319
X-Content-Type-Options →nosniff
X-FRAME-OPTIONS →SAMEORIGIN
X-Powered-By →ASP.NET
X-TFS-ProcessId →607be308-045b-4bee-ac37-b5d54909a752
X-TFS-Session →f9deb713-e32e-4756-81b6-92ae66507e11
X-VSS-E2EID →f9deb713-e32e-4756-81b6-92ae66507e11
X-VSS-UserData →e71d123d-590b-49e7-a136-431ed7965741:mrichman
```

**Comment by niadak** [comment]
@mrichman , Thanks for sharing your findings. Please make a GET call and see if the end point is successfully deleted or not. Share the response with us. Ideally you should not get any object.

http://tfs:8080/tfs/EcoSys/Student/_apis/distributedtask/serviceendpoints/23dbd458-b3ce-40a0-8a77-47b9adc95486?api-version=3.0-preview.1
HTTP Method : Get

**Comment by mrichman** [comment]
@niadak No, I still get the same response to a GET:

```
{"data":{"subscriptionId":"717dbfc1-958c-4a09-ba32-5fce93bbb8d6","subscriptionName":"100022-Flame_University","creationMode":"Automatic"},"id":"23dbd458-b3ce-40a0-8a77-47b9adc95486","name":"delete me","type":"azurerm","url":"https://management.azure.com/","createdBy":{"id":"e71d123d-590b-49e7-a136-431ed7965741","displayName":"Mark Richman","uniqueName":"CMC\\mrichman"},"authorization":{"parameters":{"serviceprincipalid":"","serviceprincipalkey":null,"tenantid":"a38ff870-9c86-43df-9e6b-6b01f206a398"},"scheme":"ServicePrincipal"},"isReady":false,"operationStatus":{"state":"Failed","statusMessage":"The given key was not present in the dictionary. For troubleshooting refer to <a href=\"https://go.microsoft.com/fwlink/?linkid=835898\" target=\"_blank\">link</a>."}}
```

I'm not sure how the `DELETE` would have worked anyway. I never supplied an auth header. Shouldn't I have to do that from Postman, curl, etc.?

**Comment by rajatagrawal-dev** [comment]
Hi @mrichman 
Can you try the solution suggested in [this link](https://developercommunity.visualstudio.com/content/problem/102182/cannot-remove-service-endpoints-for-subscription-t.html)

**Comment by rajatagrawal-dev** [comment]
Please mail us at RM_Customer_Queries@microsoft.com if you face this issue again.
