### ISSUE TITLE
Support for custom headers in Invoke-VSTeamRequest

### ISSUE THREAD

**Issue by kine** [DarqueWarrior/vsteam#235]
When I need to call API which have no own cmdlet in the module, like API for updating Wiki page, I need to specify e.g. If-Match header to the request. I see no way how to add this now when using Invoke-VSTeamRequest.

Adding possibility to specify own header values will allow me to use this call to cover all "unsupported" API calls.

Thanks!

**Comment by SebastianSchuetze** [comment]
Thanks for the suggestion @kine! What do you think, would you be able to suggest a PR for this enhancement?
