### ISSUE TITLE
Does VSTeams support on-premise TFS?

### ISSUE THREAD

**Issue by AnthonyAtApex** [DarqueWarrior/vsteam#236]
We have an onipremise TFS installation, which is on the latest version (Dev17.M153.3).

When I invoke the Get-VSTeamGroup commandlet, I get the following error. Are we just out of luck using this module locally?

`This account does not support the graph API.
At C:\...\PowerShell\Modules\VSTeam\6.4.3\vsteam.functions.ps1:185 char:7
+       throw 'This account does not support the graph API.'
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (This account does n\u2026port the graph API.:String) [], RuntimeException
+ FullyQualifiedErrorId : This account does not support the graph API.`

**Comment by MichelZ** [comment]
It does support it, but not that particular cmdlet, as it needs the graph API, which is not available on-premises I believe

**Comment by AnthonyAtApex** [comment]
Thanks for the info. Do you have a suggestion for getting Project / Team / Group memberships using these commandlets and on-premise? Or should I stick with rolling my own and using the REST API?

**Comment by MichelZ** [comment]
If you can do it with the REST API, then we <should> be able to do it using PS.
What way is there in the REST API?

**Comment by AnthonyAtApex** [comment]
Here's what I've been able to piece together, looks like Azure DevOps 2019 on-premise still supports the older REST APIs:
[https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/tfs/overview?view=azure-devops-2019](url)
[https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/tfs/teams?view=azure-devops-2019#GetaTeamMembers](url)

So what I've been doing is manually building my own URLs for testing:

Get All Projects
http://[servername]:8080/[collection]/[project]/_apis/projects

Get Project Info 
http://[servername]:8080/[collection]/[project]/_apis/projects/{project GUID}

Get Project Teams
http://[servername]:8080/[collection]/[project]/_apis/projects/{project GUID}/teams

Get Project Default Team Members
http://[servername]:8080/[collection]/[project]/_apis/projects/{project GUID}/teams/[team GUID}/Members

I haven't been able to discover endpoints for individual account permissions by project / team or the team permissions by project.

**Comment by MichelZ** [comment]
Yes, this API is actually still available in the latest API for 2019:
https://docs.microsoft.com/en-us/rest/api/azure/devops/core/teams/get%20team%20members%20with%20extended%20properties?view=azure-devops-server-rest-5.0

But that only gives you the Team Members, not the Project/Group Members.
Unfortunately it's all a bit limiting in this regards on-premises.

**Comment by AnthonyAtApex** [comment]
Agreed. Documentation is frustrating too.
