### ISSUE TITLE
[Feature] Add Support for Variable Groups

### ISSUE THREAD

**Issue by PlagueHO** [DarqueWarrior/vsteam#24]
As a continuous delivery and automation engineer
I would like to be able to list, add, edit and delete VSTS Variable Groups via PowerShell
So that requests from service management systems can automatically configure Variable Groups containing Azure Service Principals and other system related information consumed by release definitions.

The API endpoint for this is not documented, but it does look like it is available as part of DistributedTask:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/f4e2350b-9bd4-451b-8597-83ae9268a0f7/accessing-library-variable-groups-for-a-project-via-the-vsts-api?forum=TFService

I'm happy to look into this further and contribute a PR for the feature if this is something you'd be happy including.

**Comment by DarqueWarrior** [comment]
Let me ping the product team and see when public API is expected.

**Comment by DarqueWarrior** [comment]
Running Get-VSTeamOption shows not only is it not documented but it is still in preview.  You can tell because the releasedVersion is still 0.0.

```
PS C:\> Get-VSTeamOption | ? { $_.resourceName -eq 'variablegroups' } | fl *


id              : f5b09dd5-9d54-45a1-8b5a-1c8287d634cc
area            : distributedtask
resourceName    : variablegroups
routeTemplate   : {project}/_apis/{area}/{resource}/{groupId}
resourceVersion : 1
minVersion      : 3.1
maxVersion      : 4.1
releasedVersion : 0.0
```

**Comment by PlagueHO** [comment]
Thanks for talking to the VSTS team @DarqueWarrior - that is much appreciated. I guess 0.0 is as "preview" as you can get :grin:. Did they happen to mention if this was a planned API? If there is no plan we might as well close this one and reopen it if things change.

**Comment by DarqueWarrior** [comment]
It is coming they sent me a preliminary version of the documentation. No date, however.

**Comment by MichelZ** [comment]
https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedTask/Variablegroups/Get%20Variable%20Groups?view=azure-devops-rest-5.0

This seems to be available at least as an "official" preview now
