### ISSUE TITLE
Wiki should point to /blob/master/docs/readme.md

### ISSUE THREAD

**Issue by MichelZ** [DarqueWarrior/vsteam#246]
The Wiki link in GitHub currently points to the root README.
It would be great if it pointed to https://github.com/DarqueWarrior/vsteam/blob/master/docs/readme.md for better discoverability of the cmdlets documentation.

**Comment by SebastianSchuetze** [comment]
Not sure what you mean. Currently, there is no wiki at all here. Can you clarify. Maybe I am missing something. :-)

![image](https://user-images.githubusercontent.com/7256168/75183781-7e343f00-5743-11ea-8775-16729d876f7c.png)

**Comment by MichelZ** [comment]
When I click on Wiki as a non-collaborater, I am transported to the front page (aka readme)

I‘d suggest to create a simple single page that just has a link to the docs... (the readme is quite „large“)

**Comment by SebastianSchuetze** [comment]
I was even thinking to create GitHub pages rendered to HTML from markdown pages. Then the documentation could be a bit more elaborate and visible.

**Comment by MichelZ** [comment]
That also sounds like something that could work, yep

**Comment by MichelZ** [comment]
@DarqueWarrior changed it to have a Wiki with basic info. I think that's good enough for now :)
