### ISSUE TITLE
Change Tagline

### ISSUE THREAD

**Issue by MichelZ** [DarqueWarrior/vsteam#258]
The current Tagline of the Project is:
`PowerShell module for accessing TFS and VSTS`

Should probably be changed to to something like:
`PowerShell module for accessing TFS, Azure DevOps Service and Azure DevOps Server`

**Comment by SebastianSchuetze** [comment]
Agree @DarqueWarrior this can only be done by you.

**Comment by DarqueWarrior** [comment]
Done.
