### ISSUE TITLE
Suggestion: Cleaner Release logs with Squash Merge in PRs

### ISSUE THREAD

**Issue by SebastianSchuetze** [DarqueWarrior/vsteam#268]
@DarqueWarrior I had a look at the change logs in the GitHub release. And the change list is very long. Probably due to that every change is being shown. Shall we maybe by default squash merge changes for every PR and also in the contribution guidelines ask for a better PR title.

In that case we would get pretty descriptive change logs and at some point even think about generating the change logs automatically from GitHub releases.

**Comment by DarqueWarrior** [comment]
I am open to it.

**Comment by SebastianSchuetze** [comment]
Shall we then set the setting to allow only squash merge in the repository settings @darquewarrior? We can do the same format in the merge as we do on the current changeling. Also with markdown and mentions for shoutouts.

Also we would have a little bit more control on formatting, don't need people to change the changelog anymore.

**Comment by DarqueWarrior** [comment]
Sure sounds good.
