### ISSUE TITLE
Support multiple artifacts in Add-VSTeamRelease function

### ISSUE THREAD

**Issue by ctorrao** [DarqueWarrior/vsteam#27]
Like in the REST API, this function of Add-VSTeamRelease should allow to create a release with multiple artifacts. Right now is hardcoded to only and always exactly ONE artifact for a release definition.

Futhermore, it also should support none artifacts (empty), since it's possible through the REST API of this function.

**Comment by DarqueWarrior** [comment]
Feel free to issue a pull request. I am more than happy to accept support.
