### ISSUE TITLE
Improve cmdlet Update-VSTeamAgent

### ISSUE THREAD

**Issue by SebastianSchuetze** [DarqueWarrior/vsteam#278]
As discussed earlier with @DarqueWarrior the PR #273 is good, but some changes should be improved:

* command should be renamed to Update-VSTeamAgentSoftware
* also by default the cmdlet should give a warning as it does on the UI (see screenshot below). This means the SupportsShouldProcess should be added to the function so the -force flag has to be used to deactivate the confirmation manually
* the related unit tests should be moved to an extra file named Update-VSTeamAgentSoftware.Tests.ps1

![image](https://user-images.githubusercontent.com/7256168/76360322-0bb78780-631d-11ea-8fd1-0482cd58f7e6.png)

**Comment by DarqueWarrior** [comment]
I will take care of this today.

**Comment by woehrl01** [comment]
Great improvement ideas! If you need help, just raise your hand.

**Comment by DarqueWarrior** [comment]
Thanks for the PR @woehrl01 I really appreciate the support. The changes are making their way through the pipeline now. Hope to have a new release soon.

**Comment by SebastianSchuetze** [comment]
This is done with one of the last releases, although we left the cmdlet name as it is. :-)
