### ISSUE TITLE
Restructure Unit Tests into one file per cmdlet

### ISSUE THREAD

**Issue by SebastianSchuetze** [DarqueWarrior/vsteam#279]
Currently, the structure of the unit test is insufficient. Sometimes multiple cmdlets have been grouped within one file and sometimes one cmdlet has its own unit test file.

@DarqueWarrior and I figured it could be better and cleaner to separate all cmdlets in their own test files for a better overview. Also, it would be much more intuitive and you would know where to find existing unit tests as well as where to put new ones.

**Comment by DarqueWarrior** [comment]
Done.
