### ISSUE TITLE
Is there any way to add Team Members? 

### ISSUE THREAD

**Issue by Wauna** [DarqueWarrior/vsteam#28]
I feel bad asking this, but is there a way to add a VSTS Group to a Project using this?  I cannot see where to add Team Members. We're using this to migrate 1,300 projects to TFS... I can't set them up manually, and am looking for a way to add a Member to Contributors for all projects I create.  

Any thoughts? 

Thanks for the great work all !!!

**Comment by kevinbowman** [comment]
I'm really interested in this feature, as it was the reason I came across this libray, looking for this feature.  We are migrating from TFS to VSTS also.  I want to stand up projects with consistent security settings applying group permissions to teams, Code and Service Endpoints.  This could be a great module, with a huge demand for features coming from people looking to migrate to VSTS.

**Comment by DarqueWarrior** [comment]
I did not add the team member functions. That was added from a pull request. Feel free to issue a pull request so we can add to the module.

**Comment by DarqueWarrior** [comment]
They just published an API. http://cda.ms/4b
I think @KeesV might issue a PR for this.
