### ISSUE TITLE
Adding a project yields this error

### ISSUE THREAD

**Issue by kevinbowman** [DarqueWarrior/vsteam#29]
I tried to create my first project using Team, and I got this issue, although the project appears to be created successfully as I would expect.  (My pat has all scopes as a collection admin)

![image](https://user-images.githubusercontent.com/19746567/33171333-9840fdcc-d043-11e7-8319-c9561083b4ab.png)

Thanks

Kevin.

**Comment by DarqueWarrior** [comment]
Thanks I will look into it. But to be clear it appears the project was created?  If so this was the function trying to retrieve the newly created project to display to you.

**Comment by GPugnet** [comment]
I am facing the same issue with Team 0.1.34.
The error occurs, but the project is created.
