### ISSUE TITLE
Add error trapping when a call to the API makes it to _callAPI without account being set

### ISSUE THREAD

**Issue by jhoneill** [DarqueWarrior/vsteam#304]
Currently if a the calling function does not do it's own check for _getInstance, or by looking at [VSTeamVersions]::account, and dives into _call API an error is thrown that "relative URLs are not supported " because the URL is built without the protocol and host name. 

I've added something to catch this and give a specific error.

**Comment by SebastianSchuetze** [comment]
@jhoneill you are confusing me a bit here. You linked a commit from your repository. Is there a PR containing this change? In the same commit, you also edited something else.
Can you clarify or link the PR here if it already exists?

**Comment by SebastianSchuetze** [comment]
found it myself.

**Comment by DarqueWarrior** [comment]
This looks like a regression. I will see what happened. Thanks for reporting this.

**Comment by DarqueWarrior** [comment]
The call to _hasAccount used to be called in _buildRequestURI that is called but _callAPI and it is missing. I will review the history of the project and track down when that got broken. Then I will decide where we return it.

**Comment by DarqueWarrior** [comment]
This was caused by the changes to remove the [dynamic parameters](https://github.com/DarqueWarrior/vsteam/pull/275).  _buildRequestURI was changed and _hasAccount removed from the method. I did not notice this in the changes coming in. I am putting the code in _buildRequestURI back the way it was.
