### ISSUE TITLE
Alligning SHiPS PSDrive properties with VSTeam module properties

### ISSUE THREAD

**Issue by stefanstranger** [DarqueWarrior/vsteam#31]
The current implementation of the SHiPS PSDrive feature does not alligns with the original VSTeam object properties.

Example:
Original VSTeam Module property members of the Build Object are:

- name
- buildNumber
- buildNumberRevision
- definition
- finishTime
- id
- keepForever
- lastChangedBy
- lastChangedDate
- logs
- orchestrationPlan
- plans
- priority
- project
- queue
- queueTime
- reason
- repository
- requestedBy
- requestedFor
- result
- retainedByRelease
- sourceBranch
- sourceVersion
- startTime
- status
- uri
- url
- _links
- definitionName
- lastChangedByUser
- projectName
- queueID
- queueName
- repositoryType
- requestedByUser
- requestedForUser

The Object properties for the SHiPS Build Object are the following:
- BuildDefinition
- BuildNumber
- BuildRequestedByUser
- BuildResult
- BuildStartTime
- BuildStatus
- Name

We need allign the properties so we can pipe object from the the drive to the functions of the vsteam module.

/Stefan

**Comment by DarqueWarrior** [comment]
Are you working on this now? Can I expect a pr?

**Comment by stefanstranger** [comment]
Yes I worked on it now. But I don't I need to get some repo permissions to create a Pull request?
