### ISSUE TITLE
Better secure Personal Access Token stored by Add-Profile cmdlet

### ISSUE THREAD

**Issue by stefanstranger** [DarqueWarrior/vsteam#33]
With the the Add-Profile Cmdlet you can create Profiles which are stored in the $home/vsteam_profiles.json file.

In this file the Personal Access Token is stored as plain text. I would suggest to secure this value better using the same technique I used for my Wunderlist Module.

Check the Set-WunderlistAuthentication function in the [Wunderlist ](https://github.com/stefanstranger/Wunderlist/blob/master/Wunderlist/Wunderlist.psm1)Module.

I can try to implement this if you want.

/Stefan

**Comment by DarqueWarrior** [comment]
A pull request with that addition would be great. Sure it would take you a lot less time than me because you have already done it before.

**Comment by DarqueWarrior** [comment]
We can reopen when we have a cross-platform solutions.
