### ISSUE TITLE
Returning all releases

### ISSUE THREAD

**Issue by stefanstranger** [DarqueWarrior/vsteam#35]
It seems that the maximum of releases being returned using the get-vsteamrelease function is 100. 

When I look at the API documentation the default value for the number of releases to get is 50.

https://www.visualstudio.com/en-us/docs/integrate/api/rm/releases

Any ideas why 100 is the maximum?

/Stefan

**Comment by DarqueWarrior** [comment]
Are you passing in a -Top?

**Comment by DarqueWarrior** [comment]
If you use -Verbose with any call you can see the actual request. 
```
GET https://loecda.vsrm.visualstudio.com/DotCom/_apis/release/releases/?api-version=4.1-preview
```
The module is not setting top so any defaults set by the API should be honored. I will log a bug on the docs.  You can override this with -Top parameter to reduce to whatever you want.

**Comment by kilasuit** [comment]
This should allow us to pull back all of the releases (even if via many requests using paginated responses) via an `-All` parameter
