### ISSUE TITLE
Get-VSTeamGitRepository fails when not specifying project name

### ISSUE THREAD

**Issue by davidroberts63** [DarqueWarrior/vsteam#36]
The docs say 'gets all repositories in your visual studio team services account, *or* a specific project'. But when running without specifying the `ProjectName` parameter the function fails.

To reproduce:

```
Add-VSTeamAccount -Account "YourAccountName" -PersonalAccessToken "YourAccessToken"
Gete-VSTeamGitRepository
```

I was expecting it to return all the git repositories within the VSTS account, across all projects.

It works fine when specifying a project name though. Just not lining up with docs and parameter requirements.

**Comment by DarqueWarrior** [comment]
Sorry for delay. Let me see what is going on.

**Comment by DarqueWarrior** [comment]
I will be submitting a fix today. Running tests now.

**Comment by DarqueWarrior** [comment]
Version 2.1.2 has the fix. Thanks again for letting me know.
