### ISSUE TITLE
Flaky Error in Windows Build

### ISSUE THREAD

**Issue by SebastianSchuetze** [DarqueWarrior/vsteam#372]
Steps to reproduce
------------------

run the build pipeline and sometimes an error comes up on the windows build

Expected behavior
-----------------

no error

Actual behavior
---------------

It sometimes comes and I just rerun the job and then it's gone. Maybe a race condition?

The error can be seen here:
https://loecda.visualstudio.com/Team%20Module/_build/results?buildId=2372&view=logs&j=df7cdcec-8c9a-591d-7383-990f35cfc117&t=997cca25-a8a0-5ab4-23ff-c5397488d326&l=52

![image](https://user-images.githubusercontent.com/7256168/96373987-3f3e7800-1170-11eb-8f9a-cb4a3f3bb1b0.png)

Environment data
----------------

OS

- [ ] macOS
- [x] Windows
- [ ] Linux

Server

- [ ] TFS 2017
- [ ] TFS 2018
- [ ] Azure DevOps Server
- [ ] Azure DevOps Service

**Comment by SebastianSchuetze** [comment]
Just as an example from PR #371 where I had to rerun two times until it worked:
https://loecda.visualstudio.com/Team%20Module/_build/results?buildId=2372&view=logs&j=2262dbd3-805d-5baf-c4b2-376411e7dee0&t=4d211eee-0186-5826-0432-824364fe4517&l=52

**Comment by jhoneill** [comment]
It's bizarre - I'm seeing it as well I can't re-trigger builds without make a change! I don't know if control returns to PowerShell before .NET has finished writing the files, but there's no build error and the file says it isn't there.

**Comment by SebastianSchuetze** [comment]
Didn't come up for a long time. Closing this for now. Maybe it has been fixed with another change.
