### ISSUE TITLE
Update azure devops release definition variable with Update-VSTeamReleaseDefinition - removes variable from definition

### ISSUE THREAD

**Issue by dariuszbz** [DarqueWarrior/vsteam#390]
I'm running the below script (vsteam 7.1.3)

$PAT ="-----------------------------"

Set-VSTeamAccount -account "https://dev.azure.com/xxx" -PersonalAccessToken $PAT

$releaseDef = Get-VSTeamReleaseDefinition -ProjectName yyy -ID 2 -Raw

$releaseDef.variables.ImageName = "abcd/jsj/laa:222"

$body = $releaseDef  | ConvertTo-Json -Depth 100

Update-VSTeamReleaseDefinition -ProjectName LLCMS -ReleaseDefinition $body

Result:
variable ImageName disappear from azure devops release pipeline definition.
 
Expected:
The new value for ImageName variable setup in azure devop release pipeline definition.

**Comment by dariuszbz** [comment]
I use powershell and azure devops api., and it works.

**Comment by DarqueWarrior** [comment]
> I use powershell and azure devops api., and it works.

If you run the command with -verbose it will dump data so you can compare what VSTeam is doing vs your code. Might help identify what is going on.

**Comment by DarqueWarrior** [comment]
@dariuszbz please let us know if this is still an issue or if we can close.

**Comment by dariuszbz** [comment]
Close. I use devops api now, and abandoned vsteam
