### ISSUE TITLE
Getting details about other repos in a multi-repo pipeline?

### ISSUE THREAD

**Issue by ebekker** [DarqueWarrior/vsteam#391]
Is it possible to use VSTeam (or more generally, the ADO REST API) to obtain details about other repos that are defined and referenced in a multi-repo pipeline?

As per the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-repositories), you can define additional repos in a YAML Pipeline which can then be pulled during a build.

At the end of the build, you can see details about these repos such as the branch and commit hash that was pulled under the **Sources** section, as can be seen in this pic:

![image](https://user-images.githubusercontent.com/3308726/115719339-fd260700-a349-11eb-868a-30f6cb328524.png)

Is it possible to retrieve these _Sources_ via VSTeam?

**Comment by SebastianSchuetze** [comment]
I am not sure. With Vs team you can do everything that is provided with the Azure DevOps API. But I believe since it is defined in the YAML itself you will be at maxim able to get info from the meta data of the pipeline run or the pipeline itself.
So if you check the API regarding the pipeline then maybe.

**Comment by SebastianSchuetze** [comment]
just checked. Maybe with this API endpoint:

https://docs.microsoft.com/en-us/rest/api/azure/devops/pipelines/runs/get?view=azure-devops-rest-6.0#repositoryresource

You can use Invoke-VSTeamRequest 

https://methodsandpractices.github.io/vsteam-docs/docs/modules/vsteam/commands/Invoke-VSTeamRequest

**Comment by ebekker** [comment]
Thanks for the suggestion.  I dug around in the APIs and played with some tests.  Unfortunately, the API only returns the "self" repo, in which the pipeline definition is itself contained in.  The strange thing is that there is also a list of "links" in the response, and one of them is a "web" link for the information which returns the rendered HTML as in the sample image I sent above.  That rendered HTML contains all the GIT sources that I'm looking for -- it's just not found in the associate REST API call.  Very weird.

Do you by any chance know where I should direct inquiries related to this to the team response for the Azure REST APIs?  Is it a GitHub repo or a UserVoice forum that I can submit the inquiry to?

Thanks again!

**Comment by ebekker** [comment]
As short-term kludge, it looks like that HTML page does contain all the details of the run in a structured form as embedded meta data in JSON.  So I was able to extract out these bits from an embedded script section, convert it from JSON and query on it.  Thanks again for the tip!

**Comment by SebastianSchuetze** [comment]
On you organization menu you should be able to get the link where you can report bugs, make suggestions and also ask question that is answered directly by the Azure DevOps product team:

![image](https://user-images.githubusercontent.com/7256168/116779704-2ba58f80-aa78-11eb-8891-79f8c7ad6897.png)

This is the feedback page:
https://developercommunity.visualstudio.com/home?space=21&stateGroup=active&ftype=idea&sort=votes&page=1

**Comment by SebastianSchuetze** [comment]
gonna close this, as this can't be done with the module.
