### ISSUE TITLE
Add-VSTeamSonarQubeEndpoint and Add-VSTeamAzureRMServiceEndpoint no longer return values

### ISSUE THREAD

**Issue by GPugnet** [DarqueWarrior/vsteam#40]
Both `Add-VSTeamSonarQubeEndpoint` and `Add-VSTeamAzureRMServiceEndpoint` no longer return values.

In v1.0.34, Endpoint details where returned : 
` return Get-ServiceEndpoint -projectName $projectName -id $resp.id`

**Comment by DarqueWarrior** [comment]
Looking into it now.

**Comment by DarqueWarrior** [comment]
2.1.4 will return that functionality.
