### ISSUE TITLE
Add-TeamAccount  -UseWindowsAuthentication

### ISSUE THREAD

**Issue by alexmags** [DarqueWarrior/vsteam#41]
Hi
Subsequent commands fail if Add-TeamAccount and login using Windows Authentication to avoid the use of plain text personal access token. 
`Add-TeamAccount -Account $vstsAccountURL -UseWindowsAuthentication -verbose

VERBOSE: Using Default Windows Credentials for authentication; no Personal Access Token required
Removed default project
VERBOSE: VSTS
VERBOSE: Git: 4.0
VERBOSE: Core: 4.0
VERBOSE: Build: 4.0
VERBOSE: Release: 4.1-preview
VERBOSE: DistributedTask: 4.1-preview
VERBOSE: MemberEntitlementManagement: 4.1-preview
PS C:\Users\alexm> get-VSTeamProject
The property 'value' cannot be found on this object. Verify that the property exists.
At C:\Users\alexm\Documents\WindowsPowerShell\Modules\vsteam\2.1.5\src\projects.psm1:110 char:31
+             foreach ($item in $resp.value) {
+                               ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict`

**Comment by DarqueWarrior** [comment]
No, it is not. -UseWindowsAuthentication is only for use with TFS. I will update the help to make that more clear. In the future, I will look into adding OAuth.  This would allow you to Auth like you do for the Azure PowerShell Module and not have to use a PAT.
