### ISSUE TITLE
 Update-VSTeamUserEntitlement not working to update user acesslevel

### ISSUE THREAD

**Issue by thahif** [DarqueWarrior/vsteam#417]
I am trying to update user accesslevel using below command and throws up an error. 

Update-VSTeamUserEntitlement -Email xxxxxxxx@gmail.com -License express

Confirm
Are you sure you want to perform this action?
Performing the operation "Update user" on target "xxxxxxxxxx (xxxxxxxx@gmail.com)".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
WARNING: The request indicated a Content-Type of "application/json-patch+" for method type "PATCH" which is not supported. Valid content types for this method are:
application/json-patch+json.
Invoke-RestMethod : {"$id":"1","innerException":null,"message":"The request indicated a Content-Type of \"application/json-patch+\" for method type \"PATCH\" which is not supported. Valid
content types for this method are: application/json-patch+json.","typeName":"Microsoft.VisualStudio.Services.WebApi.VssRequestContentTypeNotSupportedException,
Microsoft.VisualStudio.Services.WebApi","typeKey":"VssRequestContentTypeNotSupportedException","errorCode":0,"eventId":3000}
At C:\Program Files\WindowsPowerShell\Modules\VSTeam\7.4.0\vsteam.functions.ps1:266 char:18
+          $resp = Invoke-RestMethod @params
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

OS

- [ ] macOS
- [ ] Windows
- [ ] Linux

Server

- [ ] Azure DevOps Service

```powershell
> Get-VSTeamAPIVersion
PS C:\windows\system32> Get-VSTeamAPIVersion


Billing                     : 5.1-preview.1
Build                       : 5.1
Core                        : 5.1
DistributedTask             : 6.0-preview
DistributedTaskReleased     : 5.1
ExtensionsManagement        : 6.0-preview
Git                         : 5.1
Graph                       : 6.0-preview
HierarchyQuery              : 5.1-preview
MemberEntitlementManagement : 6.0-preview
Packaging                   : 6.0-preview
Pipelines                   : 5.1-preview
Policy                      : 5.1
Processes                   : 6.0-preview
Release                     : 5.1
ServiceEndpoints            : 5.0-preview
TaskGroups                  : 6.0-preview
Tfvc                        : 5.1
VariableGroups              : 5.1-preview.1
Version                     : VSTS
```

```powershell
> $PSVersionTable

PS C:\windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by thahif** [comment]
Can someone acknowledge this issue?

**Comment by SebastianSchuetze** [comment]
I can confirm it. Gonna look at it soon.

**Comment by thahif** [comment]
@SebastianSchuetze - any update here?

**Comment by SebastianSchuetze** [comment]
Unfortunately not. Private life is stopping me from doing some wanted open source work.

But if you are comfortable to try to submit a PR that from yes the core bug, then I can look at it and and adjust so you t fits well the the rest of the code.

If you do just make sure I can edit your PR.

**Comment by thahif** [comment]
With some help from stackoverflow community, I was able to get below update. 
![image](https://user-images.githubusercontent.com/25587083/140518245-ae1dc6d7-8a8c-41f4-8ecb-30b310821bd2.png)

Will this help you out?

**Comment by SebastianSchuetze** [comment]
it does

**Comment by thahif** [comment]
@SebastianSchuetze - any progress made here?

**Comment by azafefo** [comment]
I waiting to resolve this issue too. Any progress?

**Comment by SebastianSchuetze** [comment]
The bigger problem we have currently is the release pipeline. We can't release new packages properly without it and I have to find time to do it. But if you guys would be able make a simple PR you would help me a lot!

**Comment by thahif** [comment]
@SebastianSchuetze  -  I tried creating one, failed with below error. 
![image](https://user-images.githubusercontent.com/25587083/142811066-da6177e5-b863-49b8-abec-268627dcef55.png)

**Comment by SebastianSchuetze** [comment]
You need to fork the repository to your account, create a branch, make changes, create a PR bag to the "trunk" branch in this repo

works like explained in this article:
https://www.dataschool.io/how-to-contribute-on-github/

We dont give direct rights to our repo for contributor, because that could reduce quality.

**Comment by thahif** [comment]
@SebastianSchuetze  - PR raised. https://github.com/MethodsAndPractices/vsteam/pull/430/
