### ISSUE TITLE
Allow additional HTTP headers

### ISSUE THREAD

**Issue by davidroberts63** [DarqueWarrior/vsteam#43]
Before I work on this, wanted to run it by you:

I'd like to add a `-Headers` parameter to `Invoke-VSTeamRequest`. Looks like it would be simple enough to affect.

Why?
Because I'm trying to use the following endpoint:
```
https://{instance-name}.vssps.visualstudio.com/_apis/Identities?searchFilter=Identifier&filterValue={some-sid}&options=None&queryMembership=None
```
In order to get that endpoint to work correctly it requires an `Accept: application/json;api-version=1.0` header. Otherwise it returns the following error message:
```
Either descriptors or identityIds or searchFactor/factorValue must be specified
```

I have a why for all this, but I'll leave it at this for the moment.

**Comment by DarqueWarrior** [comment]
I might ping the VSTS team. It very odd that this one API would not accept the version on the query string as every other API in VSTS.  Have you tried just adding the -Version parameter to the ivr call?

**Comment by davidroberts63** [comment]
Aha, that worked like a charm. The thought didn't occur to me. Thanks for that. My mind had settled on the 'application/json' part but didn't delve deeper.

**Comment by davidroberts63** [comment]
Just one more note, -version "1.0" doesn't do the trick. But adding '&api-version=1.0' does. Looks like that's because I'm using `Invoke-VSTeamRequest -Url`. Using `-Url` doesn't let _callApi use the _buildRequestUri which is where the api-version is added.  I have to use 'Invoke-VSTeamRequest` because I need a custom querystring.

Sooo. Maybe I do a little work to give `Invoke-VSTeamRequest` a `-QueryString` parameter?

**Comment by DarqueWarrior** [comment]
I think that already works. You just set body to an object. When you are doing a get the body is the query string. I think I have that in the help.

**Comment by DarqueWarrior** [comment]
Yup. Already supported.

-Body <Object>
        Specifies the body of the request. The body is the content of the request that follows the headers. You can also pipe a body value to
        Invoke-VSTeamRequest.

        The Body parameter can be used to specify a list of query parameters or specify the content of the response.

        When the input is a GET request and the body is an IDictionary (typically, a hash table), the body is added to the URI as query
        parameters. For other GET requests, the body is set as the value of the request body in the standard name=value format.

**Comment by davidroberts63** [comment]
Hah, okay, I see what I did wrong. I've been doing `ConvertTo-Json` on the body object, removed that. Works great now. I was trying to do too much at once. Thanks for being patient with me on it.

**Comment by DarqueWarrior** [comment]
No problem!  It is really not clear that the body can be used that way. I only learned that when I read the help for the underlying Web Request call.  But once you know it is awesome.
