### ISSUE TITLE
Installation failed because 'SHiPS' module the authenticode signature is not valid.

### ISSUE THREAD

**Issue by VectorBCO** [DarqueWarrior/vsteam#449]
### Steps to reproduce

```powershell
Install-Module -Name VSTeam -Repository PSGallery -Scope CurrentUser

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the
modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
```

### Expected behavior

I expected that module will be installed.

### Actual behavior?

Install-Package: The module 'SHiPS' cannot be installed or updated because the authenticode signature of the file 'SHiPS.psd1' is not valid.

### On Which OS have you tried it?

Windows

### What was your server version?

Azure DevOps Services

### Log output of used API

```shell
-
```

### Log output of $PSVersionTable

```shell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SebastianSchuetze** [comment]
Thanks for reporting. But I don't see how we can influence this. Any idea?

**Comment by SebastianSchuetze** [comment]
If you get an error the you can still use 
```powershell
Install-Module VSTeam -Scope CurrentUser -SkipPublisherCheck
```

closing it for now. As this is a problem with the SHiPS module. We had a look at it already: #298

**Comment by VectorBCO** [comment]
my guess, that is not ok to just ignore the issue with adding skip
verification during installation process. 
In this case could be faced security violation, with not progressed results

**Comment by VectorBCO** [comment]
I have no idea who should fix this, but at least this issue should be reported to the proper team
