### ISSUE TITLE
Add-VSTeamProject is missing option to create public project

### ISSUE THREAD

**Issue by JanuszNowak** [DarqueWarrior/vsteam#469]
### Proposal

Enable Add-VSTeamProject to create public projects.

### Solved Problem

Public projects can be created.

**Comment by SebastianSchuetze** [comment]
@JanuszNowak thanks for the suggestion. I mark it as a feature, since it is not a bug. But by design it is not implemented yet.

**Comment by JanuszNowak** [comment]
@SebastianSchuetze 👍
