### ISSUE TITLE
Security API

### ISSUE THREAD

**Issue by sztaylorakgov** [DarqueWarrior/vsteam#48]
Awesome PowerShell cmdlets in VSTeam, @DarqueWarrior!  I'm on a project focused on DevOps using an AAD backed VSTS account.  I'm using VSTeam to create administration scripts, but I have to work-around some missing VSTS REST APIs using Invoke-RestMethod, specifically the VSTS Security API.  Have you or other VSTeam contributors looked at incorporating Security API operations like the VSTS [Set Access Control Entries REST API](https://docs.microsoft.com/en-us/rest/api/vsts/security/access%20control%20entries/set%20access%20control%20entries?view=vsts) into VSTeam?

**Comment by DarqueWarrior** [comment]
Not yet. Feel free to add it. I accept pull requests.

**Comment by DarqueWarrior** [comment]
Let me see if I can have someone from the VSTS team review your comments.

**Comment by sztaylorakgov** [comment]
OK, thanks. If someone has time to review, I would be interested to learn more about what the authorization problem is and whether there is a solution.  The VSTS PAT I'm using is setup for all scopes.  So, the HTTP 401 response from the Invoke-RestMethod should not be caused by a missing identity read authorization on the PAT.

**Comment by willsmythe** [comment]
I would expect your token to work in this scenario. We (VSTS team) are investigating.

**Comment by sztaylorakgov** [comment]
Thanks, @willsmythe.  To help narrow down the scenario, the VSTS account I'm using is a federated Azure AD backed account.  My user identity in the account is authorized as a Team Project Collection Administrator.  Happy to supply any other details that become relevant.

**Comment by sztaylorakgov** [comment]
@willsmythe Curious if the investigation resulted in a bug or other change on the roadmap?  In testing again today, I see I get the same behavior documented in this issue.  So, problem appears to still exist.

**Comment by davidroberts63** [comment]
I'm seeing the same thing. @willsmythe , has the VSTS team discovered anything about this? Same situation. I've tried this in an account that is AAD backed and another account that is simple Microsoft account backed.

I seem to recall past documentation of the Profile api (or almost anything at 'app.vssps.visualstudio.com') noting that PAT won't work for that. If that's the case, how would one be able to use that API at all? If there's a better place to have this discussion (given this is the PS module, not the api itself) let me know.

**Comment by MichelZ** [comment]
I am successfully able to use the Security API‘s from Powershell. Let‘s see if I get some time to contribute something here.

**Comment by MichelZ** [comment]
#144
