### ISSUE TITLE
Add -ReleaseParameters to Add-VSTeamRelease

### ISSUE THREAD

**Issue by abaganuv** [DarqueWarrior/vsteam#522]
### Proposal

In order to create a new release and pass parameters to variables need to add -ReleaseParameters to Add-VSTeamRelease

### Solved Problem

Pass variables

**Comment by SebastianSchuetze** [comment]
As stated in #521 this is nothing we can add because it is not supported with the API. Or to develop a work around and user variables would not make sense from a design standpoint.
