### ISSUE TITLE
Version in PowerShell Gallery still at 0.1.134

### ISSUE THREAD

**Issue by jamesbannan** [DarqueWarrior/vsteam#54]
Is the version in the PowerShell Gallery going to be updated? It's way behind the module version in this repository, so when you install the module using `Install-Module -Name Team` you get a very out-of-date version.

**Comment by DarqueWarrior** [comment]
You need to install VSTeam not Team.

**Comment by jamesbannan** [comment]
@DarqueWarrior It might be worth updating the link to the blog post, in that case. The article still references `Team` not `VSTeam`
