### ISSUE TITLE
Use of ternary operator in Remove-VSTeamDirectAssignment breaks module in Powershell versions < 7

### ISSUE THREAD

**Issue by justinainsworth** [DarqueWarrior/vsteam#550]
### Steps to reproduce

in powershell 5.1

import-module vsteam

### Expected behavior

i expected that the module would import.

### Actual behavior?

The module fails to import with error "Unexpected token '?' in expression or statement."

### On Which OS have you tried it?

Windows

### What was your server version?

Azure DevOps Services

### Log output of used API

```shell
N/A
```

### Log output of $PSVersionTable

```shell
N/A
```

**Comment by SebastianSchuetze** [comment]
Thx @justinainsworth . Fixing it now.
