### ISSUE TITLE
010_projects.Tests.ps1 do not work with AAD backed VSTS account

### ISSUE THREAD

**Issue by KaiWalter** [DarqueWarrior/vsteam#61]
Steps to reproduce
------------------

1. create an VSTS account backed by an Azure Active Directory
2. install SonarQube from market place into VSTS account
3. add an additional AAD user
4. set $env:API_VERSION = "VSTS"
5. set environment variables EMAIL ACCT PAT so that these are valid for the test
6. execute 010_projects.Tests.ps1 from integration\test

Expected behavior
-----------------

In a VSTS account with only MS Accounts invited the tests run successfully

```powershell
   Context Users exercise
    [+] Get-VSTeamUser Should return all users 595ms
    [+] Get-VSTeamUser ById Should return Teams 1.4s
    [+] Remove-VSTeamUser should fail 543ms
    [+] Remove-VSTeamUser should delete the team 1.72s
    [+] Add-VSTeamUser should add a team 2.03s
```

Actual behavior
---------------

When executing the tests with an AAD backed VSTS account I get an error:

```powershell
   Context Users exercise
    [+] Get-VSTeamUser Should return all users 1.22s
    [-] Get-VSTeamUser ById Should return Teams 528ms
      PropertyNotFoundException: The property 'Id' cannot be found on this object. Verify that the property exists.
      at <ScriptBlock>, C:\src\vsteam\integration\test\010_projects.Tests.ps1: line 252
    [+] Remove-VSTeamUser should fail 528ms
    [-] Remove-VSTeamUser should delete the team 634ms
      RuntimeException: Could not find user with an email equal to azuretest4@xyzcompany.com
      at Remove-VSTeamUser<Process>, C:\src\vsteam\src\users.psm1: line 152
      at <ScriptBlock>, C:\src\vsteam\integration\test\010_projects.Tests.ps1: line 261
    [+] Add-VSTeamUser should add a team 2.17s
```

Environment data
----------------

```powershell
> $VSTeamVersionTable
Name                           Value
----                           -----
Git                            3.0
DistributedTask                3.0-preview
Tfvc                           3.0
Version                        TFS2017
Release                        3.0-preview
Build                          3.0
Account
Core                           3.0
DefaultProject
ModuleVersion                  3.0.2
MemberEntitlementManagement
ServiceFabricEndpoint
```

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17134.165
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.165
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by KaiWalter** [comment]
I retested. The issue occurs when emailaddress and principalname are not identical. In my sample that would be azuretest4@xyzcompany.com != azuretest4@xyzcompany.onmicrosoft.com

However running the test azuretest4@xyzcompany.onmicrosoft.com results in another error:

```powershell
    [-] Add-VSTeamUser should add a team 3.6s
      PropertyNotFoundException: The property 'Count' cannot be found on this object. Verify that the property exists.
      at <ScriptBlock>, C:\src\vsteam\integration\test\010_projects.Tests.ps1: line 268
```

Questions:
a) Do you like me to dive into the VSTS / AAD issues?
b) I miss a getting started section for contributing
- install-module SHiPS
- EditorConfig for VS Code (when using VS Code)
- have a blank and not used VSTS account !!!
- install SonarQube to this VSTS account
where would you like (if) to place this?

**Comment by DarqueWarrior** [comment]
Sorry for the delay was heads down getting the previous version out. I am more than happy for you to submit a PR to correct any issues.

**Comment by DarqueWarrior** [comment]
I am adding a warning to the integration tests files and the contribution file. Sorry about that.

**Comment by KaiWalter** [comment]
@DarqueWarrior - OK, I'd like to take this one - can you assign it to me please

**Comment by KaiWalter** [comment]
Another observation. When running this 010 integration test repeatedly, there seems to be some service latency in 2 places:

1) in my setup ~1 out of 4 times : on time of checking ´Description´ seems not committed completely 
```
      It 'Update-VSTeamProject Should update description' {
         Update-VSTeamProject -Name $projectName -NewDescription 'Test Description' -Force

         Get-VSTeamProject -Name $projectName | Select-Object -ExpandProperty 'Description' | Should Be 'Test Description'
      }
```
resulting in
```
    [-] Update-VSTeamProject Should update description 1.13s
      Expected string length 16 but was 0. Strings differ at index 0.
      Expected: {Test Description}
      But was:  {}
      -----------^
      107:          Get-VSTeamProject -Name $projectName | Select-Object -ExpandProperty 'Description' | Should Be 'Test Description'
      at <ScriptBlock>, C:\Users\...\vsteam\integration\test\010_projects.Tests.ps1: line 107
```

2) in my setup ~1 out of 4 times : one of the preceeding `Add-VSTeamAzureRMServiceEndpoint` also seems not be processed completely
```
      It 'Remove-VSTeamServiceEndpoint Should delete service endpoints' {
         Get-VSTeamServiceEndpoint -ProjectName $newProjectName | Remove-VSTeamServiceEndpoint -ProjectName $newProjectName -Force

         Get-VSTeamServiceEndpoint -ProjectName $newProjectName | Should Be $null
      }
```
resulting in
```
  [-] Remove-VSTeamServiceEndpoint Should delete service endpoints 253ms
      WebException: The remote server returned an error: (403) Forbidden.
      at _callAPI, C:\Users\...\vsteam\src\common.ps1: line 573
      at Remove-VSTeamServiceEndpoint<Process>, C:\Users\...\vsteam\src\serviceendpoints.psm1: line 503
      at Get-VSTeamServiceEndpoint<Process>, C:\Users\...\vsteam\src\serviceendpoints.psm1: line 448
      at <ScriptBlock>, C:\Users\...\vsteam\integration\test\010_projects.Tests.ps1: line 235
```

I can reproduce this with a MSA and an AAD backed VSTS account. Just run it 10x.
May be it is also a region related problem (West Europe).

It may not seem important in context of these integration tests. However in a real world scenario it would annoy me. Adding pauses (which I tried with this issue successfully) does not seem right to me.

Let me know your thoughts.

**Comment by DarqueWarrior** [comment]
Sorry for the delay I was traveling this week. I will get back to this tomorrow.

**Comment by KaiWalter** [comment]
issue not reproducible anymore
