### ISSUE TITLE
Get-VSTeamBuildDefinition should allow access to the build process

### ISSUE THREAD

**Issue by jmezach** [DarqueWarrior/vsteam#64]
Currently it seems that Get-VSTeamBuildDefinition allows you to get metadata for a build definition, but does not allow access to the actual build process. Interestingly the Update-VSTeamBuildDefinition and Add-VSTeamBuildDefinition commands allow you to specify an input file to use as the build process.

I would like to use VSTeam to build a script to patch multiple build definitions at once, but it seems that that is not currently possible, given the above situation. Is this something to consider? I could take a stab at a PR, but I'm not sure if it fits the vision.

**Comment by DarqueWarrior** [comment]
Are all the builds you want to patch the same structure just with different projects?  If so you would export the JSON file. Then to patch you would update the JSON file and run Update-VSTeamBuildDefinition on each build def passing in the JSON file.  If each are different then I would have to understand what your patch is doing.

**Comment by KaiWalter** [comment]
I may be already heading in this direction. Please check my [PR](https://github.com/DarqueWarrior/vsteam/pull/68).

**Comment by jmezach** [comment]
@DarqueWarrior We were trying to mostly do the same patch to each of the build definitions, but based on what was already there. I've now created a separate script that just calls the API's to take care of this. It is probably a one of thing anyway, so I'm good now.

That being said, I believe there is a value in having access to the build process itself through VSTeam. I don't currently see a way of doing that, but it seems that @KaiWalter is already taking a stab at that. So as far as I'm concerned we can close this issue.

**Comment by KaiWalter** [comment]
@DarqueWarrior - I have no way to DM you right now.
I'll be off for the next 7 days. Then I can pick up this issue as I also need it for my organization.
