### ISSUE TITLE
PowerShell to get list of all Build Agents with Machine Name on which they hosted

### ISSUE THREAD

**Issue by IbrahimUmar** [DarqueWarrior/vsteam#65]
Hi
      I want to create Powershell script (with Invoke-RestMethod) to use REST API and get the build agents in TFS 2018 Project along hosted Machine Name. Kindly help me how to achieve this.  

TFS url : http://ProjectName/DefaultCollection/ScrumProject

**Comment by DarqueWarrior** [comment]
Let me do some research and see how we can get the capabilities of the agent. There it lists the computer name.

**Comment by DarqueWarrior** [comment]
Invoke-VSTeamRequest -Url http://yourTFSName:8080/tfs/defaultcollection/_apis/distributedtask/pools/1/agents | Select -ExpandProperty value
