### ISSUE TITLE
cannot able to retrive the "Authored Date" property from Get-vsteamGitRef command

### ISSUE THREAD

**Issue by TechnicalVegeta** [DarqueWarrior/vsteam#99]
Feature Request: 
Add "authored Date" property for the Get-VSTeamGitRef

Example:
Get-VSTeamGitRepository -ProjectName $projname |ForEach-Object {Get-VSTeamGitRef -ProjectName $projname -RepositoryID $_.id |select "AutoredDate"

Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

Get-VSTeamGitRepository -ProjectName $projname |ForEach-Object {Get-VSTeamGitRef -ProjectName $projname -RepositoryID $_.id |select "AutoredDate"
```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $VSTeamVersionTable

```

```powershell
> $PSVersionTable

```

**Comment by DarqueWarrior** [comment]
Do you want to the creationDate returned?

**Comment by DarqueWarrior** [comment]
@TechnicalVegeta  can you confirm it is the creationDate? If not I will close this issue.
